### ISSUE TITLE
Native ads is of templates type, failing ad load...

### ISSUE THREAD

**Issue by letuanhung1997** [AppLovin/AppLovin-MAX-Flutter#102]
### MAX Plugin Version

3.0.1

### Flutter Version

3.7.12

### Device/Platform Info

Emulator: Pixel 4 API 33

### Current Behavior

I'm trying to integrate native ads into my app and got the message "Native ads is of templates type, failing ad load...". Please, what do I need to do to fix this!
![Untitled](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/45821085/1fb494de-8fb6-450b-9bdd-5794c38738a8)

### How to Reproduce

I used the same code as the applovin_max 3.0.1 example and my sdkKey +  native Ad Unit Id:

**Comment by thomasmso** [comment]
Hi, we only support the manual integration method for native ads, not templates.

**Comment by thomasmso** [comment]
Please update your Ad Unit configuration accordingly.

**Comment by DiTuStudio** [comment]
Hello @thomasmso, I also use native manual for my app flutter and native manual work on android but not on ios. On simulator ios, the logs: show "Native ad loaded" and the next line is "Native ad is of template type, failing ad load...". Please help me

**Comment by thomasmso** [comment]
There are two types of native ads that you can configure for in your Ad Unit screen. You can select the manual/custom type instead of templates.

**Comment by DiTuStudio** [comment]
@thomasmso Thank you for your comment, but I have selected the manual type and now when I run debug mode native, inter and reward ads shown, I publish my app to appstore, inter and reward ads shown, native ads not show. What's happen ?

**Comment by thomasmso** [comment]
That is likely an issue with your integration with our plugin. I'd recommend double-checking that you are calling the right ad APIs and with the right Ad Unit Ids.
