### ISSUE TITLE
How can I implement Mediated Networks?

### ISSUE THREAD

**Issue by desmeit** [AppLovin/AppLovin-MAX-Flutter#103]
### MAX Plugin Version

3.0.1

### Flutter Version

3.7.12

### Device/Platform Info

IOS

### Current Behavior

I try to implement one of the mediated networks. I added them in the applovin console. But in the ShowMediationDebugger it misses the networks. Do I need to add the adapter SDKs of the networks separately? For example AppLovinMediationGoogleAdapter or AmazonPublisherServicesSDK?

### How to Reproduce

please see above

**Comment by thomasmso** [comment]
@desmeit - We have no Flutter support for Amazon. However, we provided native ObjC/Swift & Java/Kotlin code in the case you want to build your on plugin natively.

https://dash.applovin.com/documentation/mediation/flutter/mediation-adapters/android?network=AMAZON_MARKETPLACE_NETWORK
https://dash.applovin.com/documentation/mediation/flutter/mediation-adapters/ios?network=AMAZON_MARKETPLACE_NETWORK

**Comment by desmeit** [comment]
whats about Yandex?
