### ISSUE TITLE
Feature Request: Integrate adapters as Flutter packages

### ISSUE THREAD

**Issue by desmeit** [AppLovin/AppLovin-MAX-Flutter#104]
Please answer my question: Is it generally necessary to install the SDK separately as described on the page or is it included in the Applovin sdk? ShowMediationDebugger says the SDKs are missing.

https://dash.applovin.com/documentation/mediation/flutter/mediation-adapters/ios

![IMG_6253C67A80A4-1](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/9454529/6be3550b-5d19-430b-a01f-d9ce23fa6bb0)

**Comment by desmeit** [comment]
So, I have now tried it on my own. I simply added the pods. But I don't know if this is the right way in Flutter because the pods are installed automatically.
It would be helpful if a tutorial on Flutter could be added to the docs.

```
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'AppLovinSDK'
  pod 'AppLovinMediationGoogleAdapter'
  pod 'AppLovinMediationYandexAdapter'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

**Comment by thomasmso** [comment]
@desmeit - We're investigating better ways to install SDKs without having to go into the underlying Android / iOS projects. If you have some suggestions, we're open. 

The snippet you posted looks good to me though.

**Comment by thomasmso** [comment]
@desmeit - Fair. Let's use this thread for seeing the demand for integrating adapters as standalone Flutter packages. We'll add it to our queue in the meantime.
