### ISSUE TITLE
Can't build apk when add implementation mediation in app build.gradle file

### ISSUE THREAD

**Issue by VietNguyen392** [AppLovin/AppLovin-MAX-Flutter#105]
### MAX Plugin Version

3.0.1

### Flutter Version

3.10.6

### Device/Platform Info

Google pixel 4

### Current Behavior

when i add mediation adapter in dependencies block in build. gradle file, i can't build apk or appbundle
dependencies {
   
    implementation 'com.applovin:applovin-sdk:+'
    implementation 'com.applovin.mediation:fyber-adapter:+'
    implementation 'com.applovin.mediation:google-ad-manager-adapter:+'
    implementation 'com.applovin.mediation:google-adapter:+'
    implementation 'com.applovin.mediation:inmobi-adapter:+'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'com.applovin.mediation:ironsource-adapter:+'
    implementation 'com.applovin.mediation:vungle-adapter:+'
    implementation 'com.applovin.mediation:facebook-adapter:+'
    implementation 'com.applovin.mediation:mintegral-adapter:+'
    implementation 'com.applovin.mediation:bytedance-adapter:+'
    implementation 'com.applovin.mediation:unityads-adapter:+'

}
but when i remove mediation implemention, i can build apk and appbundle normal

### How to Reproduce

add mediation adapter in dependencies block in app/build.gradle file and then run command flutter build apk

**Comment by alhiwatan** [comment]
@VietNguyen392, I'm wondering if you have set the repositories as well.    For example, IronSouce needs both repositories and dependencies.

```
// Repos
repositories {
    google()
    mavenCentral()
    maven { url "https://android-sdk.is.com" }
}

dependencies {
    implementation 'com.applovin:applovin-sdk:+'
    implementation 'com.applovin.mediation:ironsource-adapter:+'
}
```

https://dash.applovin.com/documentation/mediation/android/mediation-adapters?network=IRONSOURCE_NETWORK

**Comment by VietNguyen392** [comment]
> @VietNguyen392, I'm wondering if you have set the repositories as well.    For example, IronSouce needs both repositories and dependencies.
> 
> 
> 
> ```
> 
> // Repos
> 
> repositories {
> 
>     google()
> 
>     mavenCentral()
> 
>     maven { url "https://android-sdk.is.com" }
> 
> }
> 
> 
> 
> dependencies {
> 
>     implementation 'com.applovin:applovin-sdk:+'
> 
>     implementation 'com.applovin.mediation:ironsource-adapter:+'
> 
> }
> 
> ```
> 
> 
> 
> https://dash.applovin.com/documentation/mediation/android/mediation-adapters?network=IRONSOURCE_NETWORK

Hi i end up by change the gradle version in build.gradle file in root level, anyway thank for the response
