### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException -[ALMyTargetMediationAdapterAdViewDelegate onLoadFailedWithError:adView:]: unrecognized selector sent to instance 0x280d22820

### ISSUE THREAD

**Issue by desmeit** [AppLovin/AppLovin-MAX-Flutter#108]
### MAX Plugin Version

3.0.1

### Flutter Version

3.7.9

### Device/Platform Info

IOS

### Current Behavior

I get this error in crashlytics:

Fatal Exception: NSInvalidArgumentException
-[ALMyTargetMediationAdapterAdViewDelegate onLoadFailedWithError:adView:]: unrecognized selector sent to instance 0x280d22820

The app is crashing.

After removing the MyTarget Adapter it is working. It seems there is an issue with the My Target Adapter.

### How to Reproduce

Adding to pod file with:

pod 'AppLovinMediationMyTargetAdapter'

**Comment by thomasmso** [comment]
Hi, this is fixed in myTarget adapter v5.18.0.1 -> https://github.com/AppLovin/AppLovin-MAX-SDK-iOS/commit/4ff65ba3c25c343dd94e806a2247cb229b715d80
