### ISSUE TITLE
Android can't close the ad because the close button is blocked by the TitleBar

### ISSUE THREAD

**Issue by randomhuangpl** [AppLovin/AppLovin-MAX-Flutter#109]
### MAX Plugin Version

3.0.1

### Flutter Version

3.10.6,

### Device/Platform Info

Android 10 ,Huawei Nova 5T YAL-L21
Android  9.0,  p36

### Current Behavior

Android can't close the ad because the close button is blocked by the TitleBar
My app theme is @android:style/Theme.Light.NoTitleBar

### Expected Behavior

Android can close the ad

### How to Reproduce

`AppLovinMAX.showInterstitial()`

### Additional Info

https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/113404168/523e1c1a-2af3-4740-bbcd-181e8dbb30b7

**Comment by thomasmso** [comment]
Hey - we're investigating and will keep this thread posted. We're not sure as to why this started happening.

**Comment by randomhuangpl** [comment]
> Hey - we're investigating and will keep this thread posted. We're not sure as to why this started happening.

We found that we only added the theme on MainActivity,   add NoTitleBar theme for Application the problem solved.
