### ISSUE TITLE
Better AppOpen Format

### ISSUE THREAD

**Issue by ycv005** [AppLovin/AppLovin-MAX-Flutter#115]
### Feature Description

hello Team, first of all thanks for the applovin plugin.

I am here to request to improve applovin's AppOpen format because on display this app open ads, it looks similar to Interstitial ads which make bad user experience.

Suggestion - I found the google's app open ad viewability much better and it make difference in user experience as well as differentiating from Interstitial Ads. Link - https://developers.google.com/ad-manager/mobile-ads-sdk/flutter/app-open

For now, I am using all applovin ads format except AppOpen since it looks similar like interestial as well as not good for user experience.

**Comment by ycv005** [comment]
@thomasmso @alhiwatan does this will be consider ahead for pipeline ?

**Comment by thomasmso** [comment]
@ycv005 - we are considering this request, but at the moment have no plans to make ad UI/UX updates.

**Comment by ycv005** [comment]
@thomasmso @alhiwatan any update?
