### ISSUE TITLE
MaxNativeAdView自定义时，无法裁剪MaxNativeAdIconView与MaxNativeAdMediaView

### ISSUE THREAD

**Issue by yuyangpl** [AppLovin/AppLovin-MAX-Flutter#116]
### Feature Description

![image](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/113407241/f4e6cabf-c29c-4070-91e1-bd7a99f02fd0)
![Simulator Screenshot - iPhone 14 Pro - 2023-08-25 at 11 54 46](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/113407241/dda83a69-6e65-44ab-9494-6eaee9dbbe9f)

需求：
设置广告图标icon以及媒体内容裁剪时，不支持设置圆形，以及其他裁剪情况；
滑动时，媒体内容会浮动在其他层上方

**Comment by jplianghu** [comment]
@yuyangpl Could you share the relevant code demonstrating your implementation of the Native Ads?

**Comment by yuyangpl** [comment]
@jplianghu Of course
[native_ad_container.txt](https://github.com/AppLovin/AppLovin-MAX-Flutter/files/12460948/native_ad_container.txt)

**Comment by yuyangpl** [comment]
Native AD custom click hot area, need to click the blank area is also triggered

**Comment by yuyangpl** [comment]
MaxNativeAdIconView and MaxNativeAdAdvertiserView Not displayed on Android

**Comment by alhiwatan** [comment]
@yuyangpl, running your code, found out that you are actually enlarging the media view.    Here is your code.   Since the `ratio` is less than 1.0, the height becomes almost twice bigger than the original.   I don't know what you are trying to do here but this is not our issue.

```
                        child: FittedBox(
                          fit: BoxFit.fill,
                          clipBehavior: Clip.antiAliasWithSaveLayer,
                          alignment: Alignment.center,
                          child: SizedBox(
                            child: MaxNativeAdMediaView(
                              width: constraints.maxWidth,
                              height: height / ratio,
                            ),
                          ),
                        ),
```

**Comment by yuyangpl** [comment]
I want to crop the media, and I want to place other components on top of the media component

**Comment by alhiwatan** [comment]
@yuyangpl, since the media image is drawn by the native method of our Android SDK, it is not easy to crop the native image in Flutter.  At the moment, we don't have a plan to support cropping in the media view.
