### ISSUE TITLE
The function AppLovinMAX.getAdaptiveBannerHeightForWidth is missing.

### ISSUE THREAD

**Issue by bruce-yan** [AppLovin/AppLovin-MAX-Flutter#117]
### MAX Plugin Version

3.0.1

### Flutter Version

3.13.0

### Device/Platform Info

Android 11

### Current Behavior

The document states that when using Adaptive Banner, I need to call AppLovinMAX.getAdaptiveBannerHeightForWidth(WIDTH), but there is no such function. How can I get the height of the Adaptive Banner?

### How to Reproduce

Calling the function will reveal that there is no such function.

**Comment by alhiwatan** [comment]
@bruce-yan, thanks for raising the issue, and let you know when it becomes available.

**Comment by alhiwatan** [comment]
@bruce-yan, we have released the fix in [3.2.0](https://github.com/AppLovin/AppLovin-MAX-Flutter/releases/tag/release_3_2_0).
