### ISSUE TITLE
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (ios/Pods/AppLovinSDK/applovin-ios-sdk-11.4.2/AppLovinSDK.xcframework)

### ISSUE THREAD

**Issue by 04pd** [AppLovin/AppLovin-MAX-Flutter#12]
Not able to install package becouse of this error

Flutter doctor -v

[✓] Flutter (Channel stable, 3.0.1, on macOS 11.6.4 20G417 darwin-x64, locale en-GB)
    • Flutter version 3.0.1 at /Users/mac/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/mac/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 68.0.4
    • Dart plugin version 221.5588

[✓] Connected device (3 available)
    • iPhone SE (2nd generation) (mobile) • 3EE9564C-A6E7-4B6D-B17A-E3C99101E50F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 11.6.4 20G417
      darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 103.0.5060.53
    ! Error: iPhone SE 2020 is not connected. Xcode will continue when iPhone SE 2020 is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by thomasmso** [comment]
Do you have `use_frameworks!` in your `Podfile`? If so, could you try removing that? Or sending over your `Podfile` for us to repro locally?

**Comment by 04pd** [comment]
> 

i do that but app crash in initialize since another packages like google ads generating errors

**Comment by thomasmso** [comment]
If you're using MAX, you shouldn't need to explicitly add Google Ads in your Podfile

**Comment by 04pd** [comment]
> If you're using MAX, you shouldn't need to explicitly add Google Ads in your Podfile

that's true, but if i   comment use_frameworks! , other libraries stop working. i also removed google ad.

**Comment by thomasmso** [comment]
Can you send over your `Podfile`?

**Comment by 04pd** [comment]
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  #  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

**Comment by 04pd** [comment]
any update on issue? i need to publish my app on appstore.

**Comment by thomasmso** [comment]
Can you try the fix [here](https://github.com/AppLovin/AppLovin-MAX-Flutter/issues/12) locally?

**Comment by 04pd** [comment]
removing use_framworks! cause other dependecy issues , so that header files of other libraries wouldn't found
