### ISSUE TITLE
max_native_ad_view.dart:224:44: Error: Member not found: 'MediaQuery.devicePixelRatioOf'.

### ISSUE THREAD

**Issue by CoolSoftMatias** [AppLovin/AppLovin-MAX-Flutter#120]
### Feature Description

Hi, 

I'm having a problem, I'm trying set a banner but I can't run the app through the following error: 

Member not found: 'MediaQuery.devicePixelRatioOf'.

The code I have for the banner is: 

  Future<void> initializePlugin() async {
    // logStatus("Initializing SDK...");

    Map? configuration = await AppLovinMAX.initialize("SDK_KEY");
    if (configuration != null) {
      _isInitialized = true;

      // logStatus("SDK Initialized: $configuration");

      attachAdListeners();
    }
  }

  void attachAdListeners() {

    /// Banner Ad Listeners
    AppLovinMAX.setBannerListener(AdViewAdListener(onAdLoadedCallback: (ad) {
      // logStatus('Banner ad loaded from ${ad.networkName}');
    }, onAdLoadFailedCallback: (adUnitId, error) {
      // logStatus('Banner ad failed to load with error code ${error.code} and message: ${error.message}');
    }, onAdClickedCallback: (ad) {
      // logStatus('Banner ad clicked');
    }, onAdExpandedCallback: (ad) {
      // logStatus('Banner ad expanded');
    }, onAdCollapsedCallback: (ad) {
      // logStatus('Banner ad collapsed');
    }, onAdRevenuePaidCallback: (ad) {
      // logStatus('Banner ad revenue paid: ${ad.revenue}');
    }));

  }

And:

bottomNavigationBar: 

        MaxAdView(
            adUnitId: "Banner_ID",
            adFormat: AdFormat.banner,
        ),

Sorry for my english

**Comment by himanshudeveloper** [comment]
also i same issue

**Comment by himanshudeveloper** [comment]
@CoolSoftMatias  simply upgrade your flutter version to [3.13.3] your issue got resolved

**Comment by alhiwatan** [comment]
@CoolSoftMatias, thanks for reporting this issue.   

According to the Flutter doc, using specific methods such as `MediaQuery.devicePixelRatioOf` is preferred rather than `MediaQuery.of(context).devicePixelRatio`.   But, it is essential to support our library regardless of the Flutter version.   Let us update.

**Comment by CoolSoftMatias** [comment]
Updating my flutter version I could run the app, and test ads appear. But the app downloaded from the play store is not showing ads, I live in Argentina works fine here?

**Comment by thomasmso** [comment]
@CoolSoftMatias - Live ads are not guarnateed to fill - that's where we suggest integrating more mediated networks to fill in the demand.
