### ISSUE TITLE
get revenue precision for a given ad

### ISSUE THREAD

**Issue by uditrugman** [AppLovin/AppLovin-MAX-Flutter#124]
### Feature Description

looking at the docs, it appears that there is a function GetRevenuePrecision that can tell the accuracy of a given ad which does not exist for flutter.

I really need a method to detect the accuracy in order to better estimate ceilling (custom API).

Is there any estimate when/if this method will be available for flutter?
any alternative to get that data?

Thanks

**Comment by alhiwatan** [comment]
Fixed in https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/128.
