### ISSUE TITLE
Native ad is of template type with manual type

### ISSUE THREAD

**Issue by Rileyjrjohns** [AppLovin/AppLovin-MAX-Flutter#126]
### MAX Plugin Version

3.2.0

### Flutter Version

3.13.5

### Device/Platform Info

Android 13

### Current Behavior

Hey, 

I got a message "Native ad is of template type, failing ad load..."
My configuration is Ok for me, i initialize like this 
![Capture d’écran 2023-10-01 à 12 10 30](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/58285390/d4259d85-7513-4930-8279-deda8f57b8d4)
and build the ad like the exemple in the documentation.
![Capture d’écran 2023-10-01 à 12 12 41](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/58285390/71a744e9-c5a5-4433-9eee-28d666dc59c1)
and i'm in test mode.
What did i miss ? 
 

### How to Reproduce

Following the setup in the documentation

**Comment by alhiwatan** [comment]
@Rileyjrjohns, do you still have the issue?   It takes ~30mins for the new settings to work.

**Comment by Rileyjrjohns** [comment]
@alhiwatan Hello, thanks for your reply. It didn't change anything :/

**Comment by Sarun1001** [comment]
Is there any fix yet ? same issue here on both ios & android, followed official documentation to implement native ad. Banner & interstitial working fine

**Comment by Rileyjrjohns** [comment]
@alhiwatan bump

**Comment by alhiwatan** [comment]
@Rileyjrjohns, Do you mind enabling and providing [verbose logs](https://dash.applovin.com/documentation/mediation/flutter/getting-started/advanced-settings#enable-verbose-logging)?

**Comment by Rileyjrjohns** [comment]
> @Rileyjrjohns, Do you mind enabling and providing [verbose logs](https://dash.applovin.com/documentation/mediation/flutter/getting-started/advanced-settings#enable-verbose-logging)?

The only error i got @alhiwatan is "Native ad is of template type, failing ad load..."
I just use meta ads for now, because i can't use app lovin ;/

**Comment by alhiwatan** [comment]
@Rileyjrjohns, the template for your native ads is **Small**.   It has to be **Manual** for the Flutter native ads.

https://dash.applovin.com/documentation/mediation/flutter/ad-formats/native-manual#native-ads

**Comment by Rileyjrjohns** [comment]
@alhiwatan thanks, it finally work :)

**Comment by ManhBanh** [comment]
@Rileyjrjohns how did you fix it? I set manual template but it still didn't work, the output was like yours : 
![Screenshot 2023-11-16 132541](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/52659954/db04a897-b8b1-48e9-b8a7-e4e332ccc47a)

**Comment by Rileyjrjohns** [comment]
hey @ManhBanh, tbh i tried a lot of things. Also, i unchecked mediation for now, i will use it when the product will be launch. Did you init the sdk ? And set your testing device ?

**Comment by ManhBanh** [comment]
@Rileyjrjohns  yes i did. I use emulator so it's already a test device

![sdk_init](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/52659954/b061b34d-64d5-44ab-8468-d5e49bfa89e8)

**Comment by Rileyjrjohns** [comment]
@ManhBanh you use it as mediation with unity ads ? Because you see under your applovin ads
Test device can be registered with only one ad network. So if you set it with unity, you need to change network. 
Also for testing purpose, i'd set it to applovin network. Later on, i'll set mediation, when the app will be published. 
![Capture d’écran 2023-11-17 à 09 45 45](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/58285390/1dad1ef2-29bb-49e6-9eea-2d7dcf3039b2)

**Comment by ManhBanh** [comment]
@Rileyjrjohns  thank you! I set Applovin as test network already. Anyway, when run the app in release mode, ads work normally :)

![test_device](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/52659954/d738d0d6-3330-406d-bf10-81a907f70cfe)
