### ISSUE TITLE
banner and mrec cannot be consistent with the width of the phone. Is this a normal phenomenon or a bug

### ISSUE THREAD

**Issue by zhangruiyu** [AppLovin/AppLovin-MAX-Flutter#131]
### MAX Plugin Version

3.1.0

### Flutter Version

3.13.7

### Device/Platform Info

android

### Current Behavior

banner and mrec cannot be consistent with the width of the phone. Is this a normal phenomenon or a bug
Part of the AD can be consistent with the width, but some ads can't

### How to Reproduce

examples of current projects used

### Additional Info

![12721697446577_ pic](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/10591822/97da0bda-c5b1-408e-b391-2207757a8eb3)

**Comment by alhiwatan** [comment]
@zhangruiyu, this is normal.  In our MAX ads, banners are 320x50, and mrecs are 300x250.   You can find more about standard ad sizes on the Internet.
