### ISSUE TITLE
BannerAD stretched and blurred in simulator  if add some Adapter in Podfile 

### ISSUE THREAD

**Issue by randomhuangpl** [AppLovin/AppLovin-MAX-Flutter#134]
### MAX Plugin Version

3.3.0

### Flutter Version

3.13.8

### Device/Platform Info

iOS 15 Pro Max Simulator

 (Xcode 15.0)

### Current Behavior

BannerAD stretched and blurred while add some Adapter in IOS 

### How to Reproduce

Add some adapter in Podfile like this:
`
target 'Runner' do
  use_frameworks!
  use_modular_headers!
    pod 'AppLovinSDK'
    pod 'AppLovinMediationInMobiAdapter'
    pod 'AppLovinMediationVungleAdapter'
    pod 'AppLovinMediationFacebookAdapter'
    pod 'AppLovinMediationByteDanceAdapter'
    pod 'AppLovinMediationTapjoyAdapter'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end
`

Run example and tap "Show Widget Banner"
![screenshot-20231107-180006](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/113404168/c0f3ab30-64bf-4462-adab-7d40a0b6200a)

### Additional Info
If no adapter is added, everything will be fine
![screenshot](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/113404168/7aa5188b-a461-47da-a502-d36ed3e0e0bd)

_No response_

**Comment by applovinAsh** [comment]
Hi @randomhuangpl, I cannot create the issue on a physical iOS device. Can you run the demo application on an actual device and see if you can see the same issue? 

I will look into banner rendering on the simulator and see if there is anything we can do about it.

**Comment by randomhuangpl** [comment]
> Hi @randomhuangpl, I cannot create the issue on a physical iOS device. Can you run the demo application on an actual device and see if you can see the same issue?
> 
> I will look into banner rendering on the simulator and see if there is anything we can do about it.

Thanks reply. Work in physical iOS device well. only in iOS simulator.
