### ISSUE TITLE
onRewarded the arguments['rewardAmount'] is int 

### ISSUE THREAD

**Issue by XiangNanLi** [AppLovin/AppLovin-MAX-Flutter#14]
`
else if ("OnRewardedAdReceivedRewardEvent" == method) {
        var reward = MaxReward(int.parse(arguments["rewardAmount"]), arguments["rewardLabel"]);
`

throw a exception

`
_TypeError (type 'int' is not a subtype of type 'String')
`

**Comment by thomasmso** [comment]
Seems related to this: https://github.com/AppLovin/AppLovin-MAX-Flutter/issues/2#issuecomment-1161515564, will fix

**Comment by thomasmso** [comment]
PR: https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/15

**Comment by thomasmso** [comment]
Fixed in 1.0.5: https://github.com/AppLovin/AppLovin-MAX-Flutter/releases/tag/release_1_0_5

**Comment by XiangNanLi** [comment]
OK, had resolved.

**Comment by XiangNanLi** [comment]
OK, had resolved.
