### ISSUE TITLE
setConsentFlowDebugUserGeography doesn't change consentFlowUserGeography

### ISSUE THREAD

**Issue by eli1stark** [AppLovin/AppLovin-MAX-Flutter#158]
### MAX Plugin Version

3.4.1

### Flutter Version

3.16.4

### Device/Platform Info

iOS  17.1.2

### Current Behavior

When you set your country to GDPR during initialization flow via:

`AppLovinMAX.setConsentFlowDebugUserGeography(ConsentFlowUserGeography.gdpr)`

`AppLovinMAX.initialize(key)` 

returns 

`{consentFlowUserGeography: O, isTestModeEnabled: true, consentDialogState: 2, hasUserConsent: false, countryCode: US, appTrackingStatus: N, isDoNotSell: false, isAgeRestrictedUser: false}`

### Expected Behavior

`initialize` 

should return 

`{consentFlowUserGeography: 1, isTestModeEnabled: true, consentDialogState: 2, hasUserConsent: false, countryCode: US, appTrackingStatus: N, isDoNotSell: false, isAgeRestrictedUser: false}`

### How to Reproduce

Set debug country to GDPR being physically in US and call `AppLovinMAX.initialize(your_key)`;

### Additional Info

I want to note that it works as expected during Google UMP Automation flow, it shows correct prompts based on the country. The only issue is that `initialize` returns the wrong value.

**Comment by santoshbagadi** [comment]
@eli1stark thank you for bringing this to our attention. Currently this is the expected behavior, but I'm curious as to what the use case is where you are expecting the `consentFlowUserGeography` to be `GDPR` when the debug setting is enabled.

**Comment by eli1stark** [comment]
@santoshbagadi It makes it difficult to test behavior that depends on this value. For example, when I use this value to show custom prompts. It's easier to test this behavior during debug mode, especially for AppLovin ads, because I am able to setup test mode in debug. It's very hard to test this behavior in production when you are located outside the GDPR country.

**Comment by alhiwatan** [comment]
This issue is stale due to inactivity and will be closed. If this is an error or you have more info, please reopen.
