### ISSUE TITLE
Meta's ad are not working

### ISSUE THREAD

**Issue by fan-mi-baba** [AppLovin/AppLovin-MAX-Flutter#159]
### MAX Plugin Version

3.0.1

### Flutter Version

3.16.0

### Device/Platform Info

iOS iPhone15

### Current Behavior

All ads can be displayed in test mode
<img src="https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/101761162/ebf0d20f-8b0b-405d-a51d-38efb281c9ce" width="240">　　<img src="https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/101761162/e5879f12-6a6e-4d4d-86c8-b4fbaf1a7403" width="240">

### Expected Behavior

All ad types return 204 in live and test mode.

### Environment
- iPhone15 (OS17.3)
- Xcode deployment target iOS 15

Referred this [docs](https://dash.applovin.com/documentation/mediation/flutter/mediation-adapters/ios?network=FACEBOOK_MEDIATE).

Write your `AppDelegate.swift` like below:
```
import UIKit
import AppTrackingTransparency
import Flutter
import Firebase
import FBAudienceNetwork

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()

    GeneratedPluginRegistrant.register(with: self)

    FBAdSettings.setDataProcessingOptions([])
    let status = ATTrackingManager.trackingAuthorizationStatus

    if (status == ATTrackingManager.AuthorizationStatus.authorized) {
      FBAdSettings.setAdvertiserTrackingEnabled(true)
    } else {
      FBAdSettings.setAdvertiserTrackingEnabled(false)
    }

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
```
and initialize `AppLovinMax`in main.dart

```
void main() async {

  AppLovinMAX.setVerboseLogging(true);
  AppLovinMAX.setIsAgeRestrictedUser(false);
  AppLovinMAX.setHasUserConsent(true);
  AppLovinMAX.setDoNotSell(false);

  AppLovinMAX.initialize([APPLOVIN_MAX_SDK_KEY]);

}
``` 

### Additional Info

- The device IDFA is added to Testing in AppLovin MAX and Meta's Ad Manager.
  - also set them to testing mode
- `NSUserTrackingUsageDescription` is set in Info.plist.
- Facebook app is installed on device and logged in with testing account.
- I've connected some mediation networks, but cannot use only meta sdk.

**Comment by thomasmso** [comment]
Here are some of the other requirements to be able to display Meta test ads:
- Meta's ATE and LDU flag needs to be set ([docs](https://dash.applovin.com/documentation/mediation/flutter/mediation-adapters/ios?network=FACEBOOK_MEDIATE#meta-audience-network-data-processing-options)).
- Our SDK's [COPPA (ageRestrictedUser) flag](https://dash.applovin.com/documentation/mediation/flutter/getting-started/privacy#prohibition-on-ads-to,-and-personal-information-from,-children-and-apps-exclusively-designed-for,-or-exclusively-directed-to,-children) needs to be set.
- App needs to be live and installed from the App or Play Store.
- Will only bid in California if [CCPA](https://dash.applovin.com/documentation/mediation/flutter/getting-started/privacy#multi-state-consumer-privacy-laws) flag is set.
- Does not fill for new apps that are not on the latest version of their SDK.
- App needs to be approved by Meta (live ads only).

Additionally, you can check this checklist for further criteria for Meta ad serving https://developers.facebook.com/tools/property/checklist.

**Comment by fan-mi-baba** [comment]
Thanks your reply.
Sure, we set ATE and LDU, and out app isn't revealed in California. And we use the latest SDK.

Can we check your ads on app which installed from not AppStore but TestFlight?

And we've already know about that debugger, but don't know how to use it., but we almost explore the meta site...

**Comment by thomasmso** [comment]
@fan-mi-baba - If this is blocking your release, I suggest ensuring that your AppLovin MAX and Meta dashboards for your account are set up correctly, then push your integration live - the data will tell you if you are getting impressions or not from Meta.

**Comment by fan-mi-baba** [comment]
We're sorry.
It works, it was enable to check imp by installed from TestFlight for production
