### ISSUE TITLE
Add support to use banner ads as widget 

### ISSUE THREAD

**Issue by 04pd** [AppLovin/AppLovin-MAX-Flutter#16]

**Comment by appstarsbiblia** [comment]
Whoever developed this lib doesn't understand how flutter works, when will the banners come out as a widget?

**Comment by johnmollaghan** [comment]
Firstly we all owe a deal of gratitude to the authors of this plugin. It is working great in my app for both interstitials and banners, so a BIG thank you for that.
It would of course be nice to have the banner as a widget and I am sure this is in the plans.

**Comment by sheribaloch** [comment]
facing same issue as I cannot use it as widget.

**Comment by appstarsbiblia** [comment]
I'm currently using an unofficial widget that works with a widget, I wanted to use the official one, is there any possibility to include the banners as a widget?

**Comment by hkpatel201** [comment]
> If someone point me to the appropriate Flutter docs, I can build it.

I am using this plugin and they are providing proper banner. May be you can get some idea from there.
https://pub.dev/packages/unity_ads_plugin/example

**Comment by DewminaUdayashan** [comment]
Thank your very much for the official plugin.
Since Flutter is fast growing framework and while there aren't any good stable flutter plugin for Applovin ads, I hope that we will be able to show Banners and MRECs in a custom ad widget by using official plugin very soon.

**Comment by thomasmso** [comment]
I can look into this in an upcoming weekend (July 16th/17th)

**Comment by ts8ta** [comment]
> I can look into this in an upcoming weekend (July 16th/17th)

Thanks for looking into this. Will this also help / enable using native ads?
Thanks!

**Comment by appstarsbiblia** [comment]
> I can look into this in an upcoming weekend (July 16th/17th)

Hello how are you? I'm looking forward to this update.

**Comment by 04pd** [comment]
it should also add native ads support

**Comment by ts8ta** [comment]
> it should also add native ads support, if you want help ,i can ,since i have developed plugin to use applovine native for. android only.
Hi, thanks for the post. Can you share the plugin you have developed for android?

**Comment by thomasmso** [comment]
Code complete here: https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/28, should be released this week, along with docs.

**Comment by thomasmso** [comment]
Banner widget docs - https://dash.applovin.com/documentation/mediation/flutter/getting-started/banners#widget-method
MREC widget docs - https://dash.applovin.com/documentation/mediation/flutter/getting-started/mrecs#widget-method

We do not have plans for opening up native demand in Flutter plugin at the moment.
