### ISSUE TITLE
AppLovinMAX.CmpService.ShowCmpForExistingUser() not exisiting

### ISSUE THREAD

**Issue by Vollinator** [AppLovin/AppLovin-MAX-Flutter#160]
### MAX Plugin Version

3.4.1

### Flutter Version

3.16.5

### Device/Platform Info

Android

### Current Behavior

The function "AppLovinMAX.CmpService.ShowCmpForExistingUser()" to show the consent to exisiting user doesn't not exist. However, this function is defined in the documentation.

### How to Reproduce

Try to call the function after integrating applovin_max package.

**Comment by alhiwatan** [comment]
@Vollinator, thanks for raising the issue.  We are actually working on it right now.
