### ISSUE TITLE
Missing AppLovinMAX.getConsentFlowUserGeography()

### ISSUE THREAD

**Issue by centy** [AppLovin/AppLovin-MAX-Flutter#163]
### MAX Plugin Version

3.5.0

### Flutter Version

3.16

### Device/Platform Info

Android

### Current Behavior

Missing AppLovinMAX.getConsentFlowUserGeography() to check if user is in UE or not.
There is now way to show  AppLovinMAX.CmpService.ShowCmpForExistingUser() only for users who can do any change there.

### How to Reproduce

Missing in API bindings

**Comment by alhiwatan** [comment]
@centy, currently, you can check it in the SDK configuration when initializing the SDK.  `AppLovinMAX.initialize()` returns `consentFlowUserGeography` in the SDK configuration.
