### ISSUE TITLE
Exception com.applovin.mediation.nativeAds.MaxNativeAd

### ISSUE THREAD

**Issue by n-namnt** [AppLovin/AppLovin-MAX-Flutter#166]
### MAX Plugin Version

3.4.1, 3.5.0

### Flutter Version

3.16.3

### Device/Platform Info

Galaxy Tab A 7.0, Galaxy J2, Oppo A37f, Oppo A37, Oppo CPH1605, Vivo Y21L, Vivo V3, Vivo Y51A, Alps, Lenovo Mobile, Sprd, Huawei, Sharp

### Current Behavior

When I use the plugin, Firebase crash reports the following:

StandardMethodCodec.decodeEnvelope
io.flutter.plugins.firebase.crashlytics.FlutterError - PlatformException(error, Attempt to invoke interface method 'com.applovin.mediation.nativeAds.MaxNativeAd com.applovin.mediation.MaxAd.getNativeAd()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method'
package:flutter/src/services/message_codecs.dart:652

### How to Reproduce

I'm not sure how to proceed; my code aligns with the instructions. Has anyone else encountered a similar issue?

**Comment by alhiwatan** [comment]
@n-namnt, thanks for raising the issue.   We will look into it.
