### ISSUE TITLE
consentFlowUserGeography returns GDPR region for Brazil users

### ISSUE THREAD

**Issue by gkovac42** [AppLovin/AppLovin-MAX-Flutter#174]
### MAX Plugin Version

3.5.0

### Flutter Version

3.16.8

### Device/Platform Info

Android

### Current Behavior

I had multiple users from Brazil reporting that the app logic treats them as being in GDPR region. I check consentFlowUserGeography value returned by AppLovinMAX.initialize to determine if the user is in GDPR region or not:

```
AppLovinMAX.initialize(<key>)
    .then((value) {
        if (value.keys.contains('consentFlowUserGeography')) {
          Values.isGdprRegion = value['consentFlowUserGeography'] == 'G';
          }
        }
```

So `value['consentFlowUserGeography'] == 'G'` returns true for SOME users in Brazil. Others are reporting no such behaviour. Not sure if it's a bug or a part of the users are circumventing the check somehow...

### How to Reproduce

Initialize the SDK from Brazil

**Comment by alhiwatan** [comment]
@gkovac42, I'm curious how some of your users experience this issue. Could you have them run another app to see if MAX solely returns an incorrect value?

**Comment by alhiwatan** [comment]
@gkovac42, I have an update that this is a known issue on Max.  We'll update you when we fix this issue.

**Comment by alhiwatan** [comment]
This issue is stale due to inactivity and will be closed. If you have more info, please reopen.
