### ISSUE TITLE
How to disable privacy pop-up boxes in non-EU areas

### ISSUE THREAD

**Issue by Yibei-ayuo** [AppLovin/AppLovin-MAX-Flutter#175]
### MAX Plugin Version

12.1.0

### Flutter Version

3.6.0

### Device/Platform Info

Android，iOS

### Current Behavior

An ugly privacy agreement pop-up box is displayed in the non-EU area, what can I do to get rid of it?
![telegram-cloud-photo-size-5-6179239826545555464-y](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26087897/375952c4-069f-4c7b-98b6-ecd8f9f3e59f)

### Expected Behavior

An ugly privacy agreement pop-up box is displayed in the non-EU area, what can I do to get rid of it?

### How to Reproduce

When using the SDK in a non-EU area, an ugly privacy agreement pop-up box will be displayed.

**Comment by Yibei-ayuo** [comment]
My Code:
`
    if (privacyPolicyUrl != "") {
        AppLovinMAX.setTermsAndPrivacyPolicyFlowEnabled(true);
        AppLovinMAX.setPrivacyPolicyUrl(privacyPolicyUrl);
      }
      if (termsOfServiceUrl != "") {
        AppLovinMAX.setTermsOfServiceUrl(termsOfServiceUrl);
      }
      final maxResult = await AppLovinMAX.initialize(adsServiceConfig.maxKey);
`

**Comment by alhiwatan** [comment]
@Yibei-ayuo, those privacy and term settings are totally optional.  You don't have to have it.
