### ISSUE TITLE
Feature Request: Load Native Ad and Render Separately

### ISSUE THREAD

**Issue by thanh2811** [AppLovin/AppLovin-MAX-Flutter#178]
### Feature Description

How can I load a Native Ad without MaxNativeAdView Widget? Is there any method to load Ad without MaxNativeAdView  mouted like Android and IOS native SDK?
Thanks <3.

**Comment by alhiwatan** [comment]
@thanh2811, at present, we do not have the bandwidth and time required to implement this feature.   But thank you for your suggestion as to how the project can be advanced.
