### ISSUE TITLE
Test ad not showing up

### ISSUE THREAD

**Issue by linsvensson** [AppLovin/AppLovin-MAX-Flutter#18]
I'm getting these log messages on my test device.
I have set up the test device with the right GAID in the applovin dashboard .

`D/AppLovinSdk(19383): ========== NETWORKS ==========`
`D/AppLovinSdk(19383): ---------- APPLOVIN_NETWORK ----------`
`D/AppLovinSdk(19383): Status  - COMPLETE`
`D/AppLovinSdk(19383): SDK     - 11.4.4`
`D/AppLovinSdk(19383): Adapter - 11.4.4`
`D/AppLovinSdk(19383): ========== AD UNITS ==========`
`D/AppLovinSdk(19383): ---------- First_AdUnit ----------`
`D/AppLovinSdk(19383): Identifier - [REDACTED]`
`D/AppLovinSdk(19383): Format     - BANNER`
`D/AppLovinSdk(19383): ========== END ==========`
`D/AppLovinSdk(19383): [AppLovinMAX] Showing BANNER with ad unit id "[REDACTED]"`
`E/AppLovinSdk(19383): [AppLovinMAX] BANNER does not exist for ad unit id [REDACTED]`

Any ideas what could be wrong?

**Comment by Borzalic** [comment]
same issue
