### ISSUE TITLE
All working EXCEPT for iOS Interstitials, am I doing something wrong?

### ISSUE THREAD

**Issue by johnmollaghan** [AppLovin/AppLovin-MAX-Flutter#19]
I have added this plugin to a number of my Android apps and both Interstitial and Banner work great, I am using Applovin and also Meta, everything works great. I can see stats for both types of ads almost straight away after the play store puts the app live.

Then I made the exact same updates to the iOS apps, the test ads for both Interstitial and banner show up in the iOS Simulator. However, in the real released apps, when I check the Applovin reports, I am only seeing stats for the iOS bannners, no impressions seem to be there for interstitials. When I install the app from the Apple appstore, I am not seeing any interstitial ads.

Could the new 1.06 plugin fix this?  Anything else that could cause this?

**Comment by thomasmso** [comment]
Can you link to your iOS app?

**Comment by johnmollaghan** [comment]
Only on my phone right now, will the ios bundle do?

com.horseboxsoftware.lhrfree

**Comment by thomasmso** [comment]
Perhaps you can [enable verbose logging](https://dash.applovin.com/documentation/mediation/flutter/getting-started/advanced-settings#enable-verbose-logging), then send the logs over either here or my email thomas.so@applovin.com

**Comment by johnmollaghan** [comment]
Will these logs work with the ios simulator? Don't really have much access to a physical iPhone. The test ads show in the simulator.

**Comment by thomasmso** [comment]
Yeah that'll work

**Comment by thomasmso** [comment]
Will be fixed here: https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/22
