### ISSUE TITLE
Native iOs Ad is Empty

### ISSUE THREAD

**Issue by marcodecarolisidt** [AppLovin/AppLovin-MAX-Flutter#190]
### MAX Plugin Version

3.0.7

### Flutter Version

3.13.6

### Device/Platform Info

iOs  17

### Current Behavior

I tried the example code, and a widget with MaxNativeAdView bound to the native applovin AdUnit ID.
For Android, I can see the elements of the widget, but for iOS the widget is empty.
From the debugger, if I go to load the ad from the app unit ID, I see the Ad.

### How to Reproduce

Running the example code for an iOs MaxNativeAdView

**Comment by alhiwatan** [comment]
@marcodecarolisidt, could you enable and send over our SDK's [verbose logs](https://dash.applovin.com/documentation/mediation/flutter/getting-started/advanced-settings#enable-verbose-logging)?

**Comment by 1day1** [comment]
@marcodecarolisidt  check applovin ad unit 's app bundle id == ios PRODUCT_BUNDLE_IDENTIFIER  both same , match

**Comment by alhiwatan** [comment]
This issue is stale due to inactivity and will be closed. If this is an error or you have more info, please reopen.
