### ISSUE TITLE
ads jittering while scrolling in iOS pro motion devices

### ISSUE THREAD

**Issue by aytunch** [AppLovin/AppLovin-MAX-Flutter#194]
### MAX Plugin Version

3.7.0

### Flutter Version

3.19.0

### Device/Platform Info

iOS 17.2

### Current Behavior

while scrolling in iOS pro motion devices, ads jitter and jump. When scrolling stops, ads stop flickering too. This only happens on high end 90-120hz refresh rate phones.

### How to Reproduce

Put ads in a custom scrollview

**Comment by alhiwatan** [comment]
@aytunch. this sounds like a general flickering issue for iOS devices while scrolling.   Could you try the solutions available  [here](https://www.google.com/search?q=ios+scrolliview+flickering+flutter)?

**Comment by aytunch** [comment]
@alhiwatan the only flickering widgets are Applovin ads. Other widgets can be smoothly scrolled. This might be a Flutter bug on using platform channels in scrollable views. Are Applovin widgets purely in flutter or do they use platform channels?

**Comment by alhiwatan** [comment]
@aytunch, we are showing a UIView via the platform channel.

**Comment by alhiwatan** [comment]
This issue is stale due to inactivity and will be closed. If this is an error or you have more info, please reopen.
