### ISSUE TITLE
MaxNativeAdView, visible property

### ISSUE THREAD

**Issue by marcodecarolisidt** [AppLovin/AppLovin-MAX-Flutter#195]
### Feature Description

As for the 
`
MaxAdView(
                visible: _listenerNotifier.loaded,
              ),
`

Could we have the visible property for the `MaxNativeAdView` as well?

**Comment by alhiwatan** [comment]
@marcodecarolisidt, if you need it right away, wrap your native ad with `Visibility` like [this](https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/a0cb5b611d31c5896452b1905b35161c3846c17e/applovin_max/lib/src/max_ad_view.dart#L131).   We will add it to our queue.
