### ISSUE TITLE
Crash on banner platform_view_android_jni_impl

### ISSUE THREAD

**Issue by daniel102102** [AppLovin/AppLovin-MAX-Flutter#196]
### MAX Plugin Version

com.applovin:applovin-sdk:+

### Flutter Version

the newest

### Device/Platform Info

Android 13 and 14

### Current Behavior

We get the biggest amount of crashes in Google Play console as below, possibly it is connected to banner displaying:

[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1594)] Check failed: fml::jni::CheckException(env). 

backtrace:
  #00  pc 0x000000000008cdb4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #01  pc 0x0000000000438844  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #02  pc 0x00000000004654cc  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #03  pc 0x0000000000451d1c  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #04  pc 0x0000000000448e78  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #05  pc 0x0000000000448f6c  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #06  pc 0x0000000000449240  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #07  pc 0x0000000000448c34  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #08  pc 0x00000000006d14e0  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #09  pc 0x00000000006ccaa8  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #10  pc 0x00000000006d1730  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #11  pc 0x00000000006ccaa8  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #12  pc 0x00000000006d1730  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #13  pc 0x00000000006ccaa8  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #14  pc 0x00000000006d1730  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #15  pc 0x00000000006ccaa8  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #16  pc 0x00000000006cc224  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #17  pc 0x00000000006ccaa8  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #18  pc 0x00000000006d1730  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #19  pc 0x00000000006ccaa8  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #20  pc 0x00000000006d0028  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #21  pc 0x00000000006ca9f0  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #22  pc 0x000000000078ff10  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #23  pc 0x000000000078fa38  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #24  pc 0x0000000000790d28  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #25  pc 0x000000000079082c  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #26  pc 0x000000000079c638  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #27  pc 0x00000000004660c4  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #28  pc 0x0000000000469e18  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #29  pc 0x0000000000018264  /system/lib64/libutils.so (android::Looper::pollInner(int)+1060)
  #30  pc 0x0000000000017de0  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
  #31  pc 0x00000000000185e4  /system/lib64/libandroid.so (ALooper_pollOnce+100)
  #32  pc 0x0000000000469f28  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #33  pc 0x0000000000467e04  /data/app/~~5roaMrwSzjedcnPwKSbsIA==/com.gst.color.numbers.pixyfy-CdAOQBuQYC_kaXnB2wSgTw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #34  pc 0x00000000000fba4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #35  pc 0x000000000008e5f0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

### How to Reproduce

I do not have steps to reproduce, this is crash grabbed from Google Play Console

**Comment by aytunch** [comment]
same, the 3.8.0 is crashing in iOS and Android

**Comment by daniel102102** [comment]
hello Guys, is anybody from AppLovin looking on this crash?

**Comment by alhiwatan** [comment]
@aytunch, @daniel102102, could you kindly provide more info about the crash?

**Comment by daniel102102** [comment]
Crash happens only on Android 13 and Android 14, diiferent devices. Banner is placed in widget which is composing the screen together with other widgets in the view. We have disabled showing banner and number of the crashes went to zero, so we are sure that banner displaying is causing the crash.

**Comment by alhiwatan** [comment]
@minhDaiVatek, we appreciate you updating us on the issue with the stack trace. It's crucial to note that this is likely due to the way our platform SDK is specified in your app's `build. gradle` with the plus sign `+`. 

```
dependencies {
    implementation "com.applovin:applovin-sdk:+"
}
```

Our Flutter package depends on a specific AppLovin MAX SDK version, which is provided inside the package itself.  However, if you have that in your `build.gradle` with `+`, the latest version will be installed, which causes `java.lang.NoSuchMethodError` when your Flutter version is not the expected one.

Could you simply remove the dependency if you have it from your app `build.gradle`?

**Comment by minhDaiVatek** [comment]
i updated to the last version and it working now.
applovin_max: ^3.9.2
