### ISSUE TITLE
Breaks hot restart

### ISSUE THREAD

**Issue by mherbert93** [AppLovin/AppLovin-MAX-Flutter#20]
This package appears to break hot restart in flutter. It hangs and does nothing when I attempt to.

**Comment by zuzpk** [comment]
Same issue here. When we implemented it not only breaks hot restart, but also app start up is slow with blank screen for like 10 seconds.

**Comment by medalawi** [comment]
@zuzpk I have same problem my app stuck on startapp screen too ios ver are you using meta network too ?

**Comment by zuzpk** [comment]
@medalawi I have tried with a fresh project with AppLovin library only and result is same. Stuck on startapp screen (blank white)

**Comment by ipliu** [comment]
@thomasmso Use this plugin example app, run example/lib/main.dart. SDK initialized successfully for the first time.
Then don't stop the app and click run again, it will perform hot restart and the SDK is stuck on initialization.

hot restart log:
```
Performing hot restart...
Syncing files to device Nokia 3 4...
Restarted application in 1,562ms.
I/flutter (15054): Initializing SDK...
```

**Comment by thomasmso** [comment]
Which platform? It looks like you were testing on Nokia?

**Comment by ipliu** [comment]
@thomasmso Android 11

**Comment by Omi231** [comment]
@zuzpk Did you find some work around?

**Comment by iamhx** [comment]
```dart
Future<void> initializePlugin() async {
  final isInitialized = await AppLovinMAX.isInitialized();
  print(
      isInitialized); //returns true when hot restart. returns false when start debugging.
  if (isInitialized == null || !isInitialized) {
    final configuration = await AppLovinMAX.initialize(
        'sdkKey');
    if (configuration != null) {
      model.watchingAds =
          false; //notifyListener method to update a button UI.
    }
  } else {
    /* 
    isInitialized may be true, but the SDK is actually not initialized at all,
    So i explicitly did an initialize again on hot restart, but this method will await forever.
    */
    final configuration = await AppLovinMAX.initialize(
        'sdkKey'); 
    model.watchingAds = false; //this never runs.
  }
}
```

The above code is for debugging purposes. I had put this code on `initState()` so as not to 'break hot restart'. If you put it in `main()` and hot restart,  `await AppLovinMAX.initialize('sdkKey')` would make the app unresponsive. 

Workaround? I have no idea. Hope someone can provide a fix for this!

**Comment by amondnet** [comment]
#77

**Comment by thomasmso** [comment]
Live in v2.4.2, thanks to @amondnet for looking into it!
