### ISSUE TITLE
setTestDeviceAdvertisingIds has a bug

### ISSUE THREAD

**Issue by chengmengyi** [AppLovin/AppLovin-MAX-Flutter#200]
### MAX Plugin Version

0

### Flutter Version

3.8.0

### Device/Platform Info

android

### Current Behavior

 in android code, advertisingIds is empty

### Expected Behavior

 in android code, advertisingIds is empty

### How to Reproduce

 in android code, advertisingIds is empty

**Comment by alhiwatan** [comment]
@chengmengyi, this is the corresponding support page for `setTestDeviceAdvertisingIds()`.   We have yet to get one for Flutter.

https://support.applovin.com/hc/en-us/articles/13986957259149-MAX-Test-Mode

Could you follow **Troubleshooting** in the link?

**Comment by alhiwatan** [comment]
This issue is stale due to inactivity and will be closed. If this is an error or you have more info, please reopen.
