### ISSUE TITLE
MaxNativeAdIconView Circular Shape

### ISSUE THREAD

**Issue by marcodecarolisidt** [AppLovin/AppLovin-MAX-Flutter#201]
### Feature Description

I tried with ClipOval and ClipRRect, but it is not possible to change the shaper of the `MaxNativeAdIconView`,
Would it be possible to have a shape argument?

<img width="323" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/75722932/e7e077e5-d14b-498a-b659-8154e5584ab1">

**Comment by thomasmso** [comment]
Hey @marcodecarolisidt - we have not received a requested related to this, and we've already did a redesign of the icon here: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/245

I'll leave this issue open though, for any other publishers that may have a similar request.
