### ISSUE TITLE
Enabling MAX Consent Flow no found

### ISSUE THREAD

**Issue by adriancsbna** [AppLovin/AppLovin-MAX-Flutter#21]
Hello.

I am trying to activate the Consent Flow programmatically as you put in the documentation, but the functions do not exist in the Plugin.

https://dash.applovin.com/documentation/mediation/flutter/getting-started/consent-flow

Could you add them?

 AppLovinMAX.setConsentFlowEnabled(true);
 AppLovinMAX.setPrivacyPolicyUrl('https://your_company_name.com/privacy/'); // mandatory
 AppLovinMAX.setTermsOfServiceUrl('https://your_company_name.com/terms/');

**Comment by adriancsbna** [comment]
Hi @thomasmso Yes, I just tested it and it seems to work. I'll leave it like that for now. Although I would prefer to do it programmatically.

Thank you very much.

**Comment by alhiwatan** [comment]
We've now introduced the [Terms and Private Policy](https://dash.applovin.com/documentation/mediation/flutter/getting-started/terms-and-privacy-policy-flow) flow to replace the consent flow.
