### ISSUE TITLE
AppLovinMAX.initialize does not implement properly, causing freeze on Flutter side.

### ISSUE THREAD

**Issue by swordsfrog** [AppLovin/AppLovin-MAX-Flutter#210]
### MAX Plugin Version

3.9.2

### Flutter Version

any

### Device/Platform Info

any

### Current Behavior

In android class `AppLovinMAX`, `initialize` does not call `result.success` if `isPluginInitialized`. Therefore, `initialize` on Flutter side will wait forever.

```
private void initialize(final String pluginVersion, final String sdkKey, final Result result)
    {
        // Guard against running init logic multiple times
        if ( isPluginInitialized )
        {
            return;
        }

        isPluginInitialized = true;
```

### Expected Behavior

Java method is implemented correctly, so that Flutter method will return when the java method finishes.

### How to Reproduce

Call AppLovinMAX.initialize multiple times on Flutter side.

**Comment by alhiwatan** [comment]
@swordsfrog, `AppLovinMAX. initialize()` must be called only once. We found out that multiple `result.success` caused `java.lang.IllegalStateException` under some race conditions and have recently removed `result.success`.
