### ISSUE TITLE
Interstital Ad load causing Crash

### ISSUE THREAD

**Issue by ranasherry** [AppLovin/AppLovin-MAX-Flutter#214]
### MAX Plugin Version

applovin_max: ^3.9.2

### Flutter Version

3.19.x

### Device/Platform Info

Android 13

### Current Behavior

 java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lcom/applovin/sdk/AppLovinSdk;Landroid/app/Activity;)V in class Lcom/applovin/mediation/ads/MaxInterstitialAd; or its super classes (declaration of 'com.applovin.mediation.ads.MaxInterstitialAd' appears in /data/app/~~9gl9jp9BQFj3ryV6qJtEeA==/com.pk.allnetworkpackages-aGxdHEDol8M5LZ2jAlBcSw==/base.apk)
E/AndroidRuntime(16788): 	at com.applovin.applovin_max.AppLovinMAX.retrieveInterstitial(AppLovinMAX.java:1310)
E/AndroidRuntime(16788): 	at com.applovin.applovin_max.AppLovinMAX.isInterstitialReady(AppLovinMAX.java:650)
E/AndroidRuntime(16788): 	at com.applovin.applovin_max.AppLovinMAX.onMethodCall(AppLovinMAX.java:1886)
E/AndroidRuntime(16788): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime(16788): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime(16788): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(16788): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(16788): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(16788): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16788): 	at android.os.Looper.loopOnce(Looper.java:211)
E/AndroidRuntime(16788): 	at android.os.Looper.loop(Looper.java:300)
E/AndroidRuntime(16788): 	at android.app.ActivityThread.main(ActivityThread.java:8503)
E/AndroidRuntime(16788): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16788): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
E/AndroidRuntime(16788): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### Expected Behavior

Applovin was working working perfectly fine 2 days ago. but tomorrow it starts crashing on interstitial ad load and show. I even tried to change the package version. even tested some of my old app and they are also showing same behavior

### How to Reproduce

import 'dart:math';

import 'package:applovin_max/applovin_max.dart';
import 'package:flutter/foundation.dart';
import 'package:get/get.dart';

import '../../utills/app_strings.dart';

class AppLovinProvider {
  AppLovinProvider._privateConstructor();

  static final AppLovinProvider instance =
      AppLovinProvider._privateConstructor();

  final String _sdk_key = AppStrings.MAX_SDK;

  final String _interstitial_ad_unit_id = AppStrings.MAX_INTER_ID;
  // final String _rewarded_ad_unit_id = "ANDROID_REWARDED_AD_UNIT_ID";
  final String _banner_ad_unit_id = AppStrings.MAX_BANNER_ID;
  // final String _mrec_ad_unit_id = AppStrings.MAX_MREC_ID;

  // Create states
  RxBool isInitialized = false.obs;
  var interstitialLoadState = AdLoadState.notLoaded;
  var interstitialRetryAttempt = 0;
  var rewardedAdLoadState = AdLoadState.notLoaded;
  var rewardedAdRetryAttempt = 0;
  var isProgrammaticBannerCreated = false;
  var isProgrammaticBannerShowing = false;
  var isWidgetBannerShowing = false;
  var isProgrammaticMRecCreated = false;
  var isProgrammaticMRecShowing = false;
  var isWidgetMRecShowing = false;

  void init() {
    // if (kReleaseMode) {
    initializePlugin();
    // }
  }

  Future<void> initializePlugin() async {
    print("Initializing SDK...");

    Map? configuration = await AppLovinMAX.initialize(_sdk_key);
    if (configuration != null) {
      isInitialized.value = true;

      print("SDK Initialized: $configuration");
      AppLovinMAX.setVerboseLogging(false);

      // attachAdListeners();
      // AppLovinMAX.loadInterstitial(_interstitial_ad_unit_id);
      //  AppLovinMAX.createMRec(AppStrings.MAX_MREC_ID, AdViewPosition.centered);
      // AppLovinMAX.createBanner(
      //     AppStrings.MAX_BANNER_ID, AdViewPosition.bottomCenter);
    } else {
      print("SDK null");
    }
  }

  void attachAdListeners() {
    /// Interstitial Ad Listeners
    AppLovinMAX.setInterstitialListener(InterstitialListener(
      onAdLoadedCallback: (ad) {
        interstitialLoadState = AdLoadState.loaded;

        // Interstitial ad is ready to be shown. AppLovinMAX.isInterstitialAdReady(_interstitial_ad_unit_id) will now return 'true'
        print('Interstitial ad loaded from ' + ad.networkName);

        // Reset retry attempt
        interstitialRetryAttempt = 0;
      },
      onAdLoadFailedCallback: (adUnitId, error) {
        interstitialLoadState = AdLoadState.notLoaded;

        // Interstitial ad failed to load
        // We recommend retrying with exponentially higher delays up to a maximum delay (in this case 64 seconds)
        interstitialRetryAttempt = interstitialRetryAttempt + 1;

        int retryDelay = pow(2, min(6, interstitialRetryAttempt)).toInt();
        print('Interstitial ad failed to load with code ' +
            error.code.toString() +
            ' - retrying in ' +
            retryDelay.toString() +
            's');

        Future.delayed(Duration(milliseconds: retryDelay * 1000), () {
          AppLovinMAX.loadInterstitial(_interstitial_ad_unit_id);
        });
      },
      onAdDisplayedCallback: (ad) {
        print('Interstitial ad displayed');
        // AppLovinMAX.loadInterstitial(_interstitial_ad_unit_id);
        //   Future.delayed(Duration(milliseconds: 2 * 1000), () {
        // print('Interstitial ad reloading after display');

        //   AppLovinMAX.loadInterstitial(_interstitial_ad_unit_id);
        // });
      },
      onAdDisplayFailedCallback: (ad, error) {
        interstitialLoadState = AdLoadState.notLoaded;
        print('Interstitial ad failed to display with code ' +
            error.code.toString() +
            ' and message ' +
            error.message);
      },
      onAdClickedCallback: (ad) {
        print('Interstitial ad clicked');
      },
      onAdHiddenCallback: (ad) {
        interstitialLoadState = AdLoadState.notLoaded;
        Future.delayed(Duration(milliseconds: 2 * 1000), () {
          print('Interstitial ad reloading after display');

          AppLovinMAX.loadInterstitial(_interstitial_ad_unit_id);
        });
        print('Interstitial ad hidden');
      },
    ));

    /// Banner Ad Listeners
    AppLovinMAX.setBannerListener(AdViewAdListener(onAdLoadedCallback: (ad) {
      print('Banner ad loaded from ' + ad.networkName);
      AppLovinMAX.showBanner(AppStrings.MAX_BANNER_ID);
    }, onAdLoadFailedCallback: (adUnitId, error) {
      print('Banner ad failed to load with error code ' +
          error.code.toString() +
          ' and message: ' +
          error.message);
    }, onAdClickedCallback: (ad) {
      print('Banner ad clicked');
    }, onAdExpandedCallback: (ad) {
      print('Banner ad expanded');
    }, onAdCollapsedCallback: (ad) {
      print('Banner ad collapsed');
    }));

    /// MREC Ad Listeners
    AppLovinMAX.setMRecListener(AdViewAdListener(onAdLoadedCallback: (ad) {
      print('MREC ad loaded from ' + ad.networkName);
    }, onAdLoadFailedCallback: (adUnitId, error) {
      print('MREC ad failed to load with error code ' +
          error.code.toString() +
          ' and message: ' +
          error.message);
    }, onAdClickedCallback: (ad) {
      print('MREC ad clicked');
    }, onAdExpandedCallback: (ad) {
      print('MREC ad expanded');
    }, onAdCollapsedCallback: (ad) {
      print('MREC ad collapsed');
    }));
  }

  void showInterstitial() async {
    print("Interstitial ad is show is called");
    bool? isInterstitialReady =
        await AppLovinMAX.isInterstitialReady(_interstitial_ad_unit_id);
    print("return: $isInterstitialReady");
    // if (isInitialized.value && isInterstitialReady!) {

    // print("Interstitial ad ready to show");

    // }

    AppLovinMAX.showInterstitial(_interstitial_ad_unit_id);
  }
}

enum AdLoadState { notLoaded, loading, loaded }

**Comment by thomasmso** [comment]
The latest version of our Flutter plugin depends on Android v12.4.2 and iOS v12.4.1 SDKs: https://github.com/AppLovin/AppLovin-MAX-Flutter/releases/tag/release_3_9_1.

Our plugin locks in to the Android SDK version here: https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/206/files#diff-37cf2cee75b60914e3c9501fd19876d751fa4a15c6e63b6ab8e556c112dd8346R41

Can you double-check your `build.gradle` files that you are not pulling in the latest version of our Android SDK somewhere?

**Comment by ranasherry** [comment]
removing the following line from build.gradle works

     implementation 'com.applovin:applovin-sdk:+'
     
     it was automatically installing latest Applovin Android version 12.5.0 which was the main reason of the error.
