### ISSUE TITLE
Incompatible kotlin version

### ISSUE THREAD

**Issue by Omi231** [AppLovin/AppLovin-MAX-Flutter#222]
### MAX Plugin Version

3.10.0

### Flutter Version

3.22.2

### Device/Platform Info

Android 14 Emulator, Xiaomi Redmi Note 10 (Android 13 Phone)

### Current Behavior

When I run `flutter run --prod` i get following errors.

Flutter version:
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 761747bfc5 (13 days ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

ext.kotlin_version = '1.7.10'
gradle version =       8.0.2

![image](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/44071105/86f09c2b-9e28-4f58-b260-f3cfc2936d69)

### How to Reproduce

flutter run --prod in existing project after updating to applovin max using flutter pub upgrade.

**Comment by alhiwatan** [comment]
@Omi231, thank you for raising this issue. It doesn't seem that our AppLovin package is the direct cause. Several similar issues reported in the Flutter issues might be related, such as [this](https://github.com/flutter/flutter/issues/145288). Could you please take a look at those to see if they address your problem?

**Comment by Omi231** [comment]
Thank you @alhiwatan, The link you provided solved my issue.
