### ISSUE TITLE
await AppLovinMAX.initialize(initAppLovinKey) is Taking huge time to init

### ISSUE THREAD

**Issue by ycv005** [AppLovin/AppLovin-MAX-Flutter#225]
### MAX Plugin Version

applovin_max: 3.8.0 and applovin_max: ^3.10.1

### Flutter Version

Flutter (Channel stable, 3.22.0, on macOS 13.1 22C65 darwin-arm64, locale en-IN)

### Device/Platform Info

Android

### Current Behavior

I am currently initializing the AppLovinMAX SDK but it is taking so much time to init (more than 4-5 sec). I tried with 5G mobile data, 50 Mbps wifi, still same issue.
- I Thought to initialize AppLovinMAX SDK without await at starting but I fear and sure enough that Ads will not be display. Kindly, suggest or direct a better way to handle this. If this is an issue then how we can improve this. I have also `google_mobile_ads` but it initialize around 600 to 800 ms (milisecond).

Note 
- I have also enable some of mediation network from AppLovin DashBoard (AppLovin, Google Admanager, Facebook, Unity). Does more mediation network effect initializing the AppLovinMAX SDK time ?
- Even in Debug mode, it is taking more time to initialize the AppLovinMAX SDK

### Expected Behavior

Initializing the AppLovinMAX SDK should be fast enough.

### How to Reproduce

- Try a Demo verion on Real and Actual environment where Actual Ads are displayed using AppLovin Flutter Package.

**Comment by ycv005** [comment]
@alhiwatan @thomasmso Can you please help here ?

**Comment by alhiwatan** [comment]
The SDK initialization time can vary depending on your network conditions and the specific ad networks you integrate, with some ad networks potentially taking longer than others. Using a splash screen during initialization is a good idea as it provides feedback to the user while they wait. However, this will probably not decrease the total initialization time. Ultimately, how you implement this to meet your goals is up to you.

**Comment by ycv005** [comment]
@alhiwatan How I can know which network is taking so much time. I have notice that, first time initizaltion is pretty slow. While after 2nd or 3rd or so on, initialization is pretty fast.
Tried with all the applovin package - applovin_max > 4.0.0

**Comment by ycv005** [comment]
@alhiwatan @thomasmso @cemtuver-applovin  Still this is big issue for me. I need some tips to make applovin init faster. I am only using AppLovin + Meta + Liffoff + Unity + Google. In parallel, I have test with Direct integration with Google and Meta, both are quick in init. Please help here.

**Comment by cemtuver-applovin** [comment]
Hi @abdullah432! Please see [my previous comment](https://github.com/AppLovin/AppLovin-MAX-Flutter/issues/225#issuecomment-2908979583).

**Comment by ycv005** [comment]
> Hi [@ycv005](https://github.com/ycv005)! For further review, we would need to check the full unfiltered AppLovin verbose logs from your application. Could you please submit your request through our dedicated support portal and include full, unfiltered AppLovin verbose logs from your app?
> 
> To proceed, click the "Contact Support" button at the bottom of https://developers.applovin.com/, then sign in or create a new support portal account before submitting your request. Please note that the support portal account is separate from your AppLovin account.


Here is the full logs @alhiwatan @thomasmso @cemtuver-applovin 

Other Info

- I have test this via Very fast Wifi connection. Thus, logs are attached.
- Problem of load of ads or failure to init is only FIRST and FIRST time, next time, it is fast. Thus, I am not making it in await call, since it is causing huge start up load time and causing bad experience

Code snippet that I am init (this is my init at the very very begining of my app init)
```
Future<void> initializeAppLovinMAX() async {
  AppLovinMAX.setVerboseLogging(true);
  // AppLovinMAX.setTestDeviceAdvertisingIds(
  //     []);
  AppLovinMAX.initialize(AppConfig.getAppLovinSdkKey())
      .then((MaxConfiguration? configuration) async {
    if (configuration != null) {
      AppLovinMAX.showMediationDebugger();
    }
  });
}
```

[first_time_real_samsung_device_with_verbose_with_show_debugger.txt](https://github.com/user-attachments/files/20679847/first_time_real_samsung_device_with_verbose_with_show_debugger.txt)

Flutter Version
- Flutter (Channel [user-branch], 3.29.3, on macOS 13.1 22C65 darwin-arm64, locale en-IN)

applovin_version - applovin_max: ^4.5.0

android/app/buid.gradle
```
dependencies {
    implementation "androidx.multidex:multidex:2.0.1"
    implementation 'com.google.firebase:firebase-messaging:23.4.1'

    // applovin mediation
    implementation('com.android.billingclient:billing:4.0.0')
    // google ad manager via applovin mediation
    implementation 'com.applovin.mediation:google-ad-manager-adapter:+'
    // facebook audience network via applovin mediation
    implementation 'com.applovin.mediation:facebook-adapter:+'
    // unity ads via applovin mediation
    implementation 'com.applovin.mediation:unityads-adapter:+'
    implementation 'com.facebook.infer.annotation:infer-annotation:0.18.0'
    // Amazon Ads via applovin mediation
    // implementation 'com.applovin.mediation:amazon-tam-adapter:+'
    // implementation 'com.amazon.android:aps-sdk:+'
    // implementation 'com.iabtcf:iabtcf-decoder:+'

    // inmobi via applovin mediation
    implementation 'com.applovin.mediation:inmobi-adapter:+'
    implementation 'com.squareup.picasso:picasso:2.8'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    // liftoff via applovin mediation
    // implementation 'com.applovin.mediation:vungle-adapter:+'
    
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.4'
}
``` 

Request
- Please re-open the Issue (I saying I have tried fixing all the rest of Issue via DevTools i.e., networking + memory + performance, before again reaching to you. Yes, after these fixes, I got better ads impression, but again, initialization time is yet not solved by me.)


Few open quesitons
- How can I know which network ?
- I have tired Preloading of Banner Ads but when AppLovin is not Initialized, then how it will be useful ?
- I am also using google_mobile_ads via google admanager (mediation network added are meta + unity) and it is very very quick.
