### ISSUE TITLE
Not Null used instead of Null Check operator

### ISSUE THREAD

**Issue by himanshu-newstok** [AppLovin/AppLovin-MAX-Flutter#226]
### MAX Plugin Version

3.10.1

### Flutter Version

3.19.3 

### Device/Platform Info

Andorid

### Current Behavior

Getting `Null check operator used on a null value` error when i am removing a page from pageview that consist native ad.

### Expected Behavior

I should not receive this error and the unnecessary assets are disposed by garbage collector.

### How to Reproduce

Create a Pageview >>  Add native ad in pageview page. >> Remove the page from pageview and call setState();

### Additional Info

You need to switch from `!` to `?` when you dispose the controller as how you do when initializing the controller.

How you initialize the controller:
`widget.controller?.addListener(_handleControllerChanged);`

but this is how you dispose the native ad controller:
`widget.controller!.removeListener(_handleControllerChanged);`

See that `!` , you should dispose it like this:
`widget.controller?.removeListener(_handleControllerChanged);`

**Comment by alhiwatan** [comment]
@himanshu-newstok, thanks for pointing this out.  We will update this in the next release.
