### ISSUE TITLE
MaxAdView in MultiSliver has black background

### ISSUE THREAD

**Issue by jackxuechen** [AppLovin/AppLovin-MAX-Flutter#227]
### MAX Plugin Version

3.10.1

### Flutter Version

3.19.6

### Device/Platform Info

IOS 17.5.1

### Current Behavior

When a CustomScrollView adds a MaxAdView with slivers, there may be a black background on the left or right or top and bottom, but there is no black background in a normal Column.
![截屏 2024-07-02 09 53 25](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/10265395/d2c65d6d-3c4f-4c69-a42c-a0b8babeda33)

### Expected Behavior

MaxAdView does not require a background color

### How to Reproduce

This can be reproduce using the following code
```dart
import 'package:applovin_max/applovin_max.dart';
import 'package:bro_novel/widget/ad_mod/ad_helper.dart';
import 'package:flutter/material.dart';
import 'package:sliver_tools/sliver_tools.dart';

class TestPage extends StatefulWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  State<TestPage> createState() => _TestPage();
}

class _TestPage extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        physics: BouncingScrollPhysics(parent: AlwaysScrollableScrollPhysics()),
        slivers: [
          MultiSliver(children: [
            MaxAdView(
              adUnitId: ADHelper().bannerADUnitId,
              adFormat: AdFormat.banner,
            ),
          ]),
        ],
      ),
    );
  }
}

```

**Comment by alhiwatan** [comment]
@jackxuechen, thanks for raising the issue.  It looks like the width of the banner container is wider than the banner width.  Could you try live ads?   Then, you won't see the background all the time.
