### ISSUE TITLE
The 3.10.1 update causes the listener settings to be invalid after Hot Restart

### ISSUE THREAD

**Issue by CloveStranger** [AppLovin/AppLovin-MAX-Flutter#229]
### MAX Plugin Version

3.10.1

### Flutter Version

3.22.2

### Device/Platform Info

Andriod & IOS

### Current Behavior

After the plugin version 3.10.1 was updated, after I initialized Max, I could not set the channel's monitoring events after Hot Restart, which made it impossible for me to correctly handle some callback events after the ad was hidden.
![img_v3_02cs_d7538039-24ba-4ba1-a9e5-91ee6a4685bg](https://github.com/user-attachments/assets/4d1b977b-d5cb-435f-b891-843d83dfc5b4)

### Expected Behavior

Version 3.10.0 can be set normally

### How to Reproduce

Initialize Max, then Hot Restart

### Additional Info

Setting the channel in advance can solve the problem

**Comment by jgrandchavin** [comment]
Same for me

**Comment by yasin-snck** [comment]
same
