### ISSUE TITLE
Failed to prepare native ad for interaction

### ISSUE THREAD

**Issue by dogiaplinh** [AppLovin/AppLovin-MAX-Flutter#230]
### MAX Plugin Version

3.10.0

### Flutter Version

3.22.0

### Device/Platform Info

Android 12, Samsung Galaxy A90 5G

### Current Behavior

Yandex native ad shown but not clickable

### How to Reproduce

- Create native ad unit, ad yandex network
- Start app, open Mediation Debugger, select Live Network Yandex

### Additional Info

Logcat error:

D/AppLovinSdk(  964): [AppLovinMAX] Native ad loaded: MediatedAd{thirdPartyAdPlacementId=R-M-3695923-2, adUnitId=600dc06311d1e62a, format=NATIVE, networkName='Yandex'}
E/AppLovinSdk(  964): [MaxNativeAdLoader] Failed to prepare native ad for interaction...

**Comment by alhiwatan** [comment]
@dogiaplinh, thank you for raising the issue. Is this reproducible with any other ad network besides Yandex, such as AppLovin, or does it occur only with Yandex?
