### ISSUE TITLE
ios NSInvalidArgumentException

### ISSUE THREAD

**Issue by aniealss** [AppLovin/AppLovin-MAX-Flutter#238]
### MAX Plugin Version

3.10.1

### Flutter Version

3.22

### Device/Platform Info

ios 16

### Current Behavior

crash

### How to Reproduce

AppLovinMAX.m
-[AppLovinMAX retrieveRewardedAdForAdUnitIdentifier:] + 1371
AppLovinMAX.m
-[AppLovinMAX loadRewardedAdForAdUnitIdentifier:] + 791
\AppLovinMAX.m
-[AppLovinMAX handleMethodCall:result:] + 2224

**Comment by alhiwatan** [comment]
@aniealss, thank you for reporting the issue! To assist with the investigation, please provide a detailed stack trace and, if possible, steps to reproduce the problem.  Also, try the latest version to see if the issue has been resolved.
