### ISSUE TITLE
Invalid Data safety form issue when submit android app to google play

### ISSUE THREAD

**Issue by khoa-superfine** [AppLovin/AppLovin-MAX-Flutter#239]
### MAX Plugin Version

12.6.0

### Flutter Version

3.10.1

### Device/Platform Info

Android

### Current Behavior

App was reject when upload to google play

### Expected Behavior

App upload to google play successful

### How to Reproduce

Submit app to production

### Additional Info

Issue details

We found an issue in the following area(s):

Version code 1: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address), Possible SDKs: com.admost.sdk:applovin, com.applovin:applovin-sdk
To bring your app into compliance, follow these steps:

com.admost.sdk:applovin com.admost.sdk:applovin: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK.
com.applovin:applovin-sdk com.applovin:applovin-sdk: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK.

**Comment by thomasmso** [comment]
@khoa-superfine - do you have a screenshot of the issue? We have not had this complaint anywhere else.

**Comment by khoa-superfine** [comment]
![image](https://github.com/user-attachments/assets/663bbc5e-4ac8-4f5c-86f9-0e72bf9103d6)
@thomasmso yes, please help to check. this is the first time I got this issue

**Comment by thomasmso** [comment]
@khoa-superfine - you might have to update your app's data safety policies to include the following:

<img width="839" alt="image" src="https://github.com/user-attachments/assets/b8ebc519-1e2f-4436-9f8c-0007729327a5">

This is an example: https://play.google.com/store/apps/datasafety?id=com.peoplefun.wordcross&hl=en_US

**Comment by khoa-superfine** [comment]
![image](https://github.com/user-attachments/assets/170d322a-d6ba-43c3-a0c3-231320691cde)
@thomasmso  Do you mean this checkbox should be checked?

**Comment by thomasmso** [comment]
Yea, could you give that a try

**Comment by khoa-superfine** [comment]
@thomasmso it's work. Thank you very much!
