### ISSUE TITLE
Initializing SDK with GDPR consent flow does not show Google UMP

### ISSUE THREAD

**Issue by francescreig** [AppLovin/AppLovin-MAX-Flutter#246]
### MAX Plugin Version

12.6.0

### Flutter Version

3.11.0

### Device/Platform Info

iOS 17.6.1

### Current Behavior

When I initialize the SDK with `AppLovinMAX.initialize(sdk_key)`, the SDK detects the that I am on the GDPR consent flow (since I am on an elegible country) but following the [documentation](https://developers.applovin.com/en/max/flutter/overview/terms-and-privacy-policy-flow#google-ump-automation), on point 2 _(Regional compliance check)_ I don't see the Google UMP dialog showing up. 

Only when I set the flag to the MAX Terms / Privacy Policy Flow to true `AppLovinMAX.setTermsAndPrivacyPolicyFlowEnabled(true)` I see the Google UMP, but I guess I we don't want to set up this.

I have set up the Google UMP correctly on the Google Admob dashboard.

### Expected Behavior

As explained on the [documentation](https://developers.applovin.com/en/max/flutter/overview/terms-and-privacy-policy-flow#google-ump-automation), once I initialize the SDK the Google UMP should show.

### How to Reproduce

0. Be on a GDPR country (or simulate it).
1. Initialize the Flutter SDK.
2. Wait until the Google UMP to show up (it won't).

**Comment by applovinAsh** [comment]
While you have the CMP set up, you still need to ensure that `AppLovinMAX.setTermsAndPrivacyFlowEnabled(true)` is set to ensure that the CMP pop-up will show to your users. You can reference our documentation for proper integration steps: https://developers.applovin.com/en/max/flutter/overview/terms-and-privacy-policy-flow#enabling-max-terms-and-privacy-policy-flow.
