### ISSUE TITLE
MainActivity.kt:11:47 Unresolved reference: getAdditionalConsentStatus

### ISSUE THREAD

**Issue by centy** [AppLovin/AppLovin-MAX-Flutter#249]
### MAX Plugin Version

12.6.1

### Flutter Version

3.11.1

### Device/Platform Info

Android

### Current Behavior

Build fails with error MainActivity.kt:11:47 Unresolved reference: getAdditionalConsentStatus

https://developers.applovin.com/en/max/flutter/preparing-mediated-networks?androidnetworks=632

val hasMetaConsent = AppLovinSdkUtils.getAdditionalConsentStatus(89, context) is not found

Gradle deps:
+--- project :applovin_max
|    +--- com.applovin:applovin-sdk:**12.6.1 -> 13.0.0**
...
+--- com.applovin.mediation:google-adapter:+ -> 23.3.0.1
|    +--- com.applovin:applovin-sdk:[13.0.0,) -> 13.0.0 (*)

### Expected Behavior

Build works

### How to Reproduce

val hasMetaConsent = AppLovinSdkUtils.getAdditionalConsentStatus(89, context)
if ( hasMetaConsent != null )
{
  // Set Meta Data Processing Options accordingly.
}
else
{
  // AC String is not available on disk. Please check for consent status after the user completes the CMP flow.
}

### Reproducible in the demo app?

Not Tested

### Additional Info

Flutter to 3.24.3

**Comment by wootaejeon** [comment]
Hi @centy, thanks for reporting the issue. We are in the process of updating our docs page to reflect the change - the `getAdditionalConsentStatus` method was migrated to `AppLovinPrivacySettings` class. Meanwhile, please refer to the code snippet below:

```
val hasMetaConsent = AppLovinPrivacySettings.getAdditionalConsentStatus(89)
if ( hasMetaConsent != null )
{
  // Set Meta Data Processing Options accordingly.
}
else
{
  // AC String is not available on disk. Please check for consent status after the user completes the CMP flow.
}
```

**Comment by wootaejeon** [comment]
@centy The link that you provided above is now updated with the above code block.
