### ISSUE TITLE
Stuck on `Initializing SDK` on hot restart and `No implementation found for method isInitialized`

### ISSUE THREAD

**Issue by asheshstha** [AppLovin/AppLovin-MAX-Flutter#25]
When I hot restart on `AppLovin MAX Demo` App, the app gets stuck on `Initializing SDK...`. Re-build works with out any issues.
<img src="https://user-images.githubusercontent.com/34856377/178134088-43eae737-70c2-4d23-b75f-7bb00de4c8c9.png " width="200" >

~~I tried to check if `AppLovinMax` re-initialization was causing the issue by calling `AppLovinMAX.isInitialized`. However, I faced another issue of `MissingPluginException (MissingPluginException(No implementation found for method isInitialized on channel applovin_max))`~~
Update: `No implementation` issue persists on `AppLovin MAX Demo` but not on `applovin_max: 1.0.8`. But the issue of sdk getting stuck on restart still persists.

`

Flutter 3.0.4
applovin_max: 1.0.8

**Comment by cmlee-danbi** [comment]
Same here but I'm developing a live app service.
And the problem only happens on AOS, not on iOS.

Flutter 3.0.5
Dart 2.17.6
applovin_max : 2.0.0

**Comment by thomasmso** [comment]
Hmm this should have been fixed in 1.0.4 (https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/9), if you're able to repro in the demo app please provide step-by-step instructions.

**Comment by cmlee-danbi** [comment]
In my case the problem was persisting the SDK instance in the GetXService class.
The GetXService class is not destroyed during hot restart unless the app is killed.
So I separated the SDK instance into HomePage 's state and the problem was solved and hot restart works fine.

Thank you!
