### ISSUE TITLE
AppLovin Max Package For Flutter show user consent dialog even after flag set

### ISSUE THREAD

**Issue by dvlprtoastguyz** [AppLovin/AppLovin-MAX-Flutter#258]
### MAX Plugin Version

4.0.0

### Flutter Version

3.22.2

### Device/Platform Info

Samsung A53

### Current Behavior

Hey There,

I am trying to implement Applovin for my flutter project and I do not want to show personalized ads for any of my users. Ultimately i do not want to show user consent dialog as I do not want to show personlized ads. I only want to show non-personalized ads in my app. I have added following code, 

```
AppLovinMAX.setTermsAndPrivacyPolicyFlowEnabled(true);
    AppLovinMAX.setPrivacyPolicyUrl(AppLovinAdManager.privacyPolicyUrl);
    AppLovinMAX.setHasUserConsent(false);
    MaxConfiguration? configuration =
        await AppLovinMAX.initialize(AppLovinAdManager.sdkKey);
    if (configuration != null) {
      AppLovinAdManager.isInitialized = true;
    }
```

I have already set the user consent dialog value to false. So it should set personalized ad settings for users to false. But still it asks for the user consent dialog for the new app install. Can you please check and help me on this?

### Expected Behavior

I want to show only non-personalized ads for my app users. So after setting te flag to false. It should not ask for user consent dialog. 

### How to Reproduce

Create new flutter project and inside main app, add the code snippet above I've provided with package version details and then try to run the app.

```
AppLovinMAX.setTermsAndPrivacyPolicyFlowEnabled(true);
    AppLovinMAX.setPrivacyPolicyUrl(AppLovinAdManager.privacyPolicyUrl);
    AppLovinMAX.setHasUserConsent(false);
    MaxConfiguration? configuration =
        await AppLovinMAX.initialize(AppLovinAdManager.sdkKey);
    if (configuration != null) {
      AppLovinAdManager.isInitialized = true;
    }
```

You can see the issue there.

### Reproducible in the demo app?

Yes

**Comment by thomasmso** [comment]
Can you remove the following LoC?

```
AppLovinMAX.setTermsAndPrivacyPolicyFlowEnabled(true); AppLovinMAX.setPrivacyPolicyUrl(AppLovinAdManager.privacyPolicyUrl);
```

By doing so, you are enabling our [MAX Terms and Privacy Policy Flow](https://developers.applovin.com/en/max/flutter/overview/terms-and-privacy-policy-flow#enabling-max-terms-and-privacy-policy-flow).
