### ISSUE TITLE
Please add support for native ads as widget

### ISSUE THREAD

**Issue by anandyadav21219** [AppLovin/AppLovin-MAX-Flutter#26]
We need to add native add support like other platforms.

**Comment by ts8ta** [comment]
Hi, thanks for your reply.
Can you let us know if this is planned at your side already?

Thomas

Anand Yadav ***@***.***> schrieb am Sa., 16. Juli 2022, 05:59:

**Comment by anandyadav21219** [comment]
Hey, I am really sorry but I don't have any plan for native ads as compared to now we are using Google and Facebook native ads instead of Applovin

**Comment by ts8ta** [comment]
OK, but native ads are already a feature of app lovin, correct?
It is just that they are not supported by flutter plug in, right?

Anand Yadav ***@***.***> schrieb am Sa., 16. Juli 2022, 07:34:

**Comment by anandyadav21219** [comment]
Yes, right

**Comment by thomasmso** [comment]
Code complete here: https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/28, should be released this week, along with docs.

**Comment by thomasmso** [comment]
Banner widget docs - https://dash.applovin.com/documentation/mediation/flutter/getting-started/banners#widget-method
MREC widget docs - https://dash.applovin.com/documentation/mediation/flutter/getting-started/mrecs#widget-method

We do not have plans for opening up native demand in Flutter plugin at the moment.

**Comment by anandyadav21219** [comment]
Can you give us approx time to come up with a native demand ad in the flutter plugin?

**Comment by thomasmso** [comment]
We do not have plans for opening up native demand in Flutter plugin at the moment.

**Comment by anandyadav21219** [comment]
okay, thank you

**Comment by thomasmso** [comment]
@anandyadav21219 - If you could, please describe how you'd imagine the API to look like and we can consider it.

**Comment by anandyadav21219** [comment]
same as the banner ads like I need to pass the native ad id and it's ready to display also it's better to have a listener in the ad.
one more thing is it's may fix in the widget not overflow or not cause problems on the screen.

**Comment by bluxiv** [comment]
Any updates on this?
I'm trying to use Facebook MREC ads but they don't seem to work as the dashboard asks for "Meta Native" which doesn't load and when configured with a normal MREC placement ID, it doesn't call at all.

**Comment by Ranashaheryar** [comment]
> Any updates on this? I'm trying to use Facebook MREC ads but they don't seem to work as the dashboard asks for "Meta Native" which doesn't load and when configured with a normal MREC placement ID, it doesn't call at all.

You will have to create Meta Native ad placement ID and put this into Max mrec Placement ID in Applovin Dashboard.

**Comment by ShahoodulHassan** [comment]
> > Any updates on this? I'm trying to use Facebook MREC ads but they don't seem to work as the dashboard asks for "Meta Native" which doesn't load and when configured with a normal MREC placement ID, it doesn't call at all.
> 
> You will have to create Meta Native ad placement ID and put this into Max mrec Placement ID in Applovin Dashboard.

Can you please describe the complete procedure of this?

**Comment by thomasmso** [comment]
We will need to update all of our adapters in order to be able to bring native ads demand to React Native. At the moment, only AppLovin demand is supported. I will update this thread once those adapters are released.

**Comment by Reketaka** [comment]
Please can you add support native ads?

**Comment by alectogeek** [comment]
Hey there!
If you need a description of how the API should look like, please, take a look at how the [google_mobile_ads](https://pub.dev/packages/google_mobile_ads) package implements native ads. 
IMHO exactly the same approach could be implemented here as well

**Comment by alectogeek** [comment]
Native ads are an important part of app monetization.
We really need the support of this kind of ad.

**Comment by rivafarabi** [comment]
I've experimented the native ads implementation on Android. you can check my [fork](https://github.com/rivafarabi/AppLovin-MAX-Flutter). It's not convenient because you need to edit the xml layout file located in the plugin folder.

![Screenshot_20230224-214255](https://user-images.githubusercontent.com/4427494/221207534-48d72310-9a4a-48b1-8553-4868bc79045d.jpg)

I haven't tried the iOS native ads, maybe next time

**Comment by rsequeirar** [comment]
> 

Thanks for your contribution. Definitely I'll check out your fork cause I want to implement native ads on my app but I didn't have time to try it by myself. Regards!

**Comment by rsequeirar** [comment]
> I've experimented the native ads implementation on Android. you can check my [fork](https://github.com/rivafarabi/AppLovin-MAX-Flutter). It's not convenient because you need to edit the xml layout file located in the plugin folder.
> 
> ![Screenshot_20230224-214255](https://user-images.githubusercontent.com/4427494/221207534-48d72310-9a4a-48b1-8553-4868bc79045d.jpg)
> 
> I haven't tried the iOS native ads, maybe next time

Thanks for your contribution. Definitely I'll check out your fork cause I want to implement native ads on my app but I didn't have time to try it by myself. Regards!

**Comment by rsequeirar** [comment]
@rivafarabi Thanks for your contribution. Definitely I'll check out your fork cause I want to implement native ads on my app but I didn't have time to try it by myself. Regards!

**Comment by anandyadav21219** [comment]
@rivafarabi Thanks a lot for your contribution but there is a slit issue, I am unable to load native ads images but the title, desc, and other things are working well, the image part is not displayed on a real device. it's working well on the emulator so please help me here

**Comment by thomasmso** [comment]
Regrettably, our current capacity does not allow us to pursue this project, and we are unable to maintain an external fork's codebase. However, if we undertake this endeavor, we will ensure to develop it comprehensively from end-to-end.

**Comment by thomasmso** [comment]
@anandyadav21219, @omi231, @alectogeek, @kreativityapps, @ts8ta, @bluxiv, @Ranashaheryar, @ShahoodulHassan, @Reketaka, @rivafarabi, @rsequeirar, @amondnet, @OttomanDeveloper - We just released Flutter plugin v3.0.0 with support for native ads. Please refer to our docs [here](https://dash.applovin.com/documentation/mediation/flutter/ad-formats/native-manual) for integration instructions.

Note that this is the initial release of the feature, so any feedback would be appreciated!

**Comment by thomasmso** [comment]
Found an issue on 3.0.0 already, fixed in 3.0.1 -> https://github.com/AppLovin/AppLovin-MAX-Flutter/releases/tag/release_3_0_1

**Comment by ycv005** [comment]
@thomasmso @alhiwatan The doc of native ads are not updated.

Reloading is confusing. Here it is not mentioned from where this variable `nativeAdViewRef ` comes.
<img width="978" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26734819/215f2894-b585-49d1-8b6c-93935def9db1">

Later digging in the codebase, I found that, native ads to be reload via nativeAdViewController. Please update it.
It should be like
_nativeAdViewController.loadAd()

**Comment by ycv005** [comment]
@thomasmso @alhiwatan , one more improvement, we can collapse body text if the text is empty. I have seen my native ads with empty text but it occupy space.

here I can see code
<img width="649" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26734819/8901af4b-12c3-4074-945e-7d40da3a9672">

**Comment by ycv005** [comment]
@thomasmso @alhiwatan 
Getting Error for Native Ads

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown during a scheduler callback.
       at _MaxNativeAdViewState._addNativeAdComponent(max_native_ad_view.dart:234)
       at MaxNativeAdMediaView.build.<fn>.<fn>(max_native_ad_view.dart:591)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1297)
       at SchedulerBinding.handleDrawFrame(binding.dart:1236)
       at SchedulerBinding._handleDrawFrame(binding.dart:1085)
```

**Comment by alhiwatan** [comment]
@ycv005, thanks for reporting the issue. Do you have any more info about the crash?  It looks like the media view is gone at the time of loading.

**Comment by ycv005** [comment]
@alhiwatan  I found the issue on firebase crashlytics dashboard. I don't have more info on it.

**Comment by alhiwatan** [comment]
Please feel free to open a new issue about the native ad.
