### ISSUE TITLE
After upgrading to xcode16, Yandex reported an error

### ISSUE THREAD

**Issue by zhouzhou94alone** [AppLovin/AppLovin-MAX-Flutter#269]
### MAX SDK Version

  applovin_max: ^4.0.0  YandexMobileAds (7.5.0):

### Device/Platform Info

xcode16

### Current Behavior

/Users/joan.z/Documents/Waifu/hiwaifu_flutter/ios/Pods/VGSLUI/VGSLUI/uikit/UIViewExtensions.swift:245:11: error: 'CACornerMask' is only available in iOS 11.0 or newer
    extension CACornerMask {
              ^

### How to Reproduce

 pod 'AppLovinMediationYandexAdapter'，An error has occurred and an upgrade is required! Currently, the code can only be modified manually.

### Reproducible in the demo app?

Yes

### Additional Info

![WeChat8a74fe6b8931d2f5fcf08d08cd20bc9c](https://github.com/user-attachments/assets/ab4526cd-9a20-4764-8278-09a99821a8d2)

**Comment by alhiwatan** [comment]
@zhouzhou94alone, I was able to build our demo app with applovin_max version 4.0.2 and AppLovinMediationYandexAdapter version 7.5.0.3 on Xcode 16.1 without any issues. Could you try again with the latest version, 7.5.0.3, of the AppLovinMediationYandexAdapter?
