### ISSUE TITLE
Flutter 3.27 Banner Ad MaxAdView not responding to Opacity

### ISSUE THREAD

**Issue by LegendAF** [AppLovin/AppLovin-MAX-Flutter#273]
### MAX Plugin Version

4.0.2

### Flutter Version

3.27.0-0.1.pre

### Device/Platform Info

iPhone 16 Pro iOS 18.1 (and every other iOS device/version [many] we tested)

### Current Behavior

Banner ad does not disappear when opacity is applied to it.

https://github.com/user-attachments/assets/68b96abd-98c3-4e44-ae1f-f1327fda5684

### Expected Behavior

Banner ad to disappear when opacity 0 is applied to it.

https://github.com/user-attachments/assets/154d532e-c661-47a7-b9ed-e5a85dad0c06

### How to Reproduce

https://github.com/LegendAF/applovin_max_flutter_broken

### Reproducible in the demo app?

Yes

### Additional Info

For what it's worth, it is also broken at the root level if you just put it outside the overlay. I included the way it is in the example because that's how we are utilizing it.

Broken on:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.27.0-0.1.pre, on macOS 15.0 24A335 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.94.2)
[✓] Connected device (5 available)
[✓] Network resources
```

Working on:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0 24A335 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.94.2)
[✓] Connected device (5 available)
[✓] Network resources
```

**Comment by alhiwatan** [comment]
@LegendAF, thank you for raising the issue with the test app. I ran the test app using the default AppLovin network, as your Podfile includes several ad networks. The banner toggles and appears to be working fine. Could you clarify if the issue is reproducible with a specific ad network?

**Comment by LegendAF** [comment]
@alhiwatan I started the app and enabled Test Mode from `AppLovinMAX.showMediationDebugger();` and I am seeing the initial issue I reported still. 

What is considered the "default AppLovin network"? 

What version of Flutter are you on?

I have also noticed if you apply the `Opacity` value directly and save (hot reload), it works. The issue seems to be around `setState` not refreshing the MaxAdView or something. I am not 100% sure.

I did a test of using `Visibility` instead of `Opacity` and it works as expected. The issue with that is `Visibility` removes the banner ad from the tree and when you toggle it back the entire ad needs to re waterfall. We are currently trying to avoid that due to other issues,

![IMG_2962](https://github.com/user-attachments/assets/908d64e8-5caa-47a0-a51f-4bd9159335a4)

https://github.com/user-attachments/assets/fed0c79f-1bda-4f42-8f51-73322fd01ee8

**Comment by LegendAF** [comment]
Yes. It works fine in 3.24.5 of Flutter. 

It is broken on the beta branch which is Flutter 3.27. You can try it out by doing `flutter channel beta` or finding version `3.27.0-0.2.pre` on whatever manager you use.

**Comment by LegendAF** [comment]
After testing on these new versions it seems like the issue has been resolved.

Flutter ` 3.27.0-0.2.pre` 
Applovin Max `4.1.1`

Flutter Doctor
```
[✓] Flutter (Channel beta, 3.27.0-0.2.pre, on macOS 15.1.1 24B2091 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)
[✓] Network resources
```
