### ISSUE TITLE
Meta ads are nor working

### ISSUE THREAD

**Issue by leon6003** [AppLovin/AppLovin-MAX-Flutter#29]
### MAX Plugin Version

1.0.8

### Flutter Version

61.2.1 (latest)

### Device/Platform Info

Android 11

### Current Behavior

Hi,

i can never get any fills from Meta. Using mediation debugger to lad test meta always gives error code 204 (no fill)
When calling "loadInterstitial" from my app there is no callback.
I spotted this in the logs 
I am running on a real phone but same behavior on emulator.

 
D/SensorManager(26284): registerListener :: 1, LSM6DSL Accelerometer, 200000, 0, com.facebook.ads.redexgen.X.96@a3eef5f
D/SensorManager(26284): registerListener :: 4, LSM6DSL Gyroscope, 200000, 0, com.facebook.ads.redexgen.X.97@c350dac

.
.
.
D/SensorManager(26284): unregisterListener :: com.facebook.ads.redexgen.X.96@a3eef5f
D/SensorManager(26284): unregisterListener :: com.facebook.ads.redexgen.X.97@c350dac

The other networks are all working. 
Anyone have a clue?

### How to Reproduce

Use the the mediation debugger on an Android with facebook installed.

**Comment by leon6003** [comment]
Update: I put on verbose logging and found this 

[AppLovinSdk] 
E/AppLovinSdk(27960): **************************************************
E/AppLovinSdk(27960): NO FILL received:
E/AppLovinSdk(27960): ..ID: "be932007fcbf83"
E/AppLovinSdk(27960): ..FORMAT: "INTER"
E/AppLovinSdk(27960): ..SDK KEY: "2IsVyoyChKgTarQg2Jfbo4pkgS45s84C2HWNW17Bd5Q8S9LbJss8bhpQd5OnT07DBK9KaBaOobOoyNKwrWo55"
E/AppLovinSdk(27960): ..PACKAGE NAME: "Hidden"
E/AppLovinSdk(27960): ..Reason: [{"code":2051,"msg":"Please set test mode for guaranteed fill"},{"code":1000,"msg":"Adnetwork missing required signal data"}]

Anyone know how to set test mode for guaranteed fill?

**Comment by Omi231** [comment]
you can add test mode device in meta audience network dashboard and it will work.

**Comment by leon6003** [comment]
Hi,
anyone knows why i suddenly get this after the latest update?

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processReleaseResources'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.applovin:applovin-sdk:+.
     Required by:
         project :app
      > Failed to list versions for com.applovin:applovin-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/applovin/applovin-sdk/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/applovin/applovin-sdk/maven-metadata.xml'.
               > Read timed out
