### ISSUE TITLE
Passing targeting data

### ISSUE THREAD

**Issue by Nikolaisd** [AppLovin/AppLovin-MAX-Flutter#30]
### Feature Description

Currently there is no way to pass targeting data, as mentioned in the docs. 
Would be nice for a future update.

**Comment by Nikolaisd** [comment]
Are there any updates on this feature?

**Comment by thomasmso** [comment]
Hi @Nikolaisd - sorry for the delay, we missed this ticket. Will have an update in the next 1-2 weeks and notify this thread when the plugin is released. Thanks!

**Comment by Nikolaisd** [comment]
Sounds great, thanks for looking into it.

**Comment by thomasmso** [comment]
Live in v2.3.0. Docs: https://dash.applovin.com/documentation/mediation/flutter/getting-started/data-passing
