### ISSUE TITLE
Very confused about the mediation (Amazon)

### ISSUE THREAD

**Issue by westlinkin** [AppLovin/AppLovin-MAX-Flutter#34]
### Feature Description

Sorry this is not a feature request.

Both [Android](https://dash.applovin.com/documentation/mediation/flutter/mediation-adapters/android?network=AMAZON_MARKETPLACE_NETWORK) and [iOS](https://dash.applovin.com/documentation/mediation/flutter/mediation-adapters/ios?network=AMAZON_MARKETPLACE_NETWORK) doc shows the native Java/Object-c code. How to integrate with Flutter using Amazon mediation? Thanks/

**Comment by thomasmso** [comment]
We currently do not have plans to support Amazon for Flutter.

**Comment by desmeit** [comment]
Is there a generally tutorial for implementing mediated Networks? There is only the info about the integration within the pod file. but how is the way to do this with flutter?

**Comment by thomasmso** [comment]
@desmeit - We have no Flutter support for Amazon. However, we provided native ObjC/Swift & Java/Kotlin code in the case you want to build your on plugin natively.

**Comment by congdanh1608** [comment]
Hi @thomasmso 
Is there any updates?
Does the Max support load amazon mediated network on Dart code.
I don't have the native plugin, just integrating Max ads in Dart code. 
I really need to support Amazon mediated network on flutter.
Thank you.

**Comment by thomasmso** [comment]
@congdanh1608 - Amazon does not have support for Flutter, do you have an approved account with them?

**Comment by congdanh1608** [comment]
> @congdanh1608 - Amazon does not have support for Flutter, do you have an approved account with them?

I am working for my client on his account.

**Comment by thomasmso** [comment]
@congdanh1608 - You can check out our docs [here](https://dash.applovin.com/documentation/mediation/flutter/mediation-adapters/android?network=AMAZON_MARKETPLACE_NETWORK). It's a pretty complex integration, different than any other mediated network, but this is a requirement by Amazon.

Depending on your client's account status with us, we might be able assist. You can send me that info via my email tw503346@gmail.com.
