### ISSUE TITLE
App crashes on using applovin and video_player in the same app

### ISSUE THREAD

**Issue by Omi231** [AppLovin/AppLovin-MAX-Flutter#36]
### MAX Plugin Version

2.0.0

### Flutter Version

3.3.0-0.1.pre

### Device/Platform Info

Redmi Note 10 Pro

### Current Behavior

App crashes after `AppLovinMAX.initialize("my sdk key here");` The error screenshot as well as pubspec.yaml dependencies are given below.

![image](https://user-images.githubusercontent.com/44071105/182694086-17d560ce-e91b-41e2-a1f5-ff40a2889dc1.png)
![image](https://user-images.githubusercontent.com/44071105/182694957-f14e0cc0-33a7-452d-aede-040d92293c76.png)

### How to Reproduce

Use ` video_player: ^2.4.5` and `applovin_max: ^2.0.0` in the same project.

**Comment by Omi231** [comment]
I even created a new test project with no other dependencies other than `video_player` and `applovin_max` and still get the same error.

![image](https://user-images.githubusercontent.com/44071105/182700234-6dc646f4-e172-4d12-b187-37c938d25c6e.png)

**Comment by ipliu** [comment]
@Omi231 The workaround is add the implementation in _android/app/build.gradle_ in your flutter project.
`implementation 'com.google.android.exoplayer:exoplayer-ui:2.18.0'`

Because the exoplayer-core:2.15.1 and exoplayer-ui:2.15.1 modules are used in applovin_max: 2.0.0.
And the exoplayer-core:2.18.0 module are used in video_player: 2.4.5.

Gradle automatically picks the higher version modules used in build.gradle, so exoplayer-core will be updated to 2.18.0, but exoplayer-ui still uses 2.15.1.

And the main problem is that the com.google.android.exoplayer2.ui.DownloadNotificationHelper class exists in both exoplayer-core:2.18.0 and exoplayer-ui:2.15.1.

**Comment by Omi231** [comment]
Thank you! that fixed the issue.

**Comment by OttomanDeveloper** [comment]
I'm also getting the same issue. When we use Video Player App and Video is playing it crashes the app. 
 
Also using Flutter Local notification plugin.


```
WARNING: [Processor] Library 'J:\AndroidStudio\Gradles\.gradle\caches\modules-2\files-2.1\com.google.android.exoplayer\exoplayer-ui\2.18.0\f9249b966775afd9a6f4d2fcd2592748df2fe8aa\exoplayer-ui-2.18.0.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/core/app/NotificationCompat$Builder'
 Example of support library reference: 'android/support/v4/media/session/MediaSessionCompat$Token'
E/AndroidRuntime(16985):        at j$.util.stream.k2.forEachOrdered(SourceFile:0)
E/AndroidRuntime(16985):        at qa.e1.m0(Unknown Source:70)
E/AndroidRuntime(16985):        at qa.e1.r(Unknown Source:13)
E/AndroidRuntime(16985):        at k1.a.g(Unknown Source:26)
E/AndroidRuntime(16985):        at i1.b$a.run(Unknown Source:210)
E/AndroidRuntime(16985):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(16985):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(16985):        at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime(16985): Caused by: java.lang.IllegalStateException: Failed to create VMBridge instance
E/AndroidRuntime(16985):        at k9.w3.d(Unknown Source:36)
E/AndroidRuntime(16985):        at k9.w3.<clinit>(Unknown Source:0)
E/AndroidRuntime(16985):        ... 30 more
```
