### ISSUE TITLE
Banner/Mrec occupy Space When not Loaded

### ISSUE THREAD

**Issue by Ranashaheryar** [AppLovin/AppLovin-MAX-Flutter#40]
### Feature Description

Banner and Mrec widget should not occupy space if these ads are not loaded. it should behave as Visibility.Gone in android

**Comment by thomasmso** [comment]
Thanks for raising this - we will review it internally.

**Comment by lelouchneo** [comment]
Is there an update on this feature.Our layout has so many holes do to this.

**Comment by thomasmso** [comment]
Apologies - we've had other internal tasks with higher priority in the pipeline.

**Comment by ycv005** [comment]
Facing same issue with Banner or MRec Ads. @thomasmso can we follow like Google Banners, they first initialise it, and they it is pass on build.

**Comment by ycv005** [comment]
I can see that the widget method, We pass directly Banner or Mrec call in build method, but if you see how the google ads load, they didn't cause space occupancy. It is important and the issue is from long time, please resolve it.
@omerhasan @thomasmso @bshikin @dpayne @applovin-mobile-engineering

**Comment by thomasmso** [comment]
Hello @ycv005,

I appreciate your feedback and the time you've taken to highlight this issue.

I also noticed that you tagged several members of the AppLovin team that was not previously on the thread. We kindly ask that future concerns be communicated as comments here. This helps us ensure a streamlined and efficient process for addressing issues.

Rest assured that your feedback is taken seriously, and we will look into this matter in a upcoming sprint.

**Comment by ycv005** [comment]
hello @thomasmso , this is pending from aug 2022, can't this be pick in this sprint ? Also, only 2 AdFormat are present in Banner. can we have more

**Comment by thomasmso** [comment]
@ycv005 - We're going to investigate in an upcoming sprint. If you are looking for more flexibility beyond banners or MRECs, you can investigate [native ads](https://dash.applovin.com/documentation/mediation/flutter/ad-formats/native-manual) to see if it suits your needs.

**Comment by ycv005** [comment]
@thomasmso Any guide for widget implement of banner ads. I have followed [this banner guide](https://dash.applovin.com/documentation/mediation/flutter/ad-formats/banners) and on my test device the ads are proper coming, showing AppLovin Max Test ads, but on real device which is on production, i am not getting impression, it is more than 3 days. Debugging in real device, only getting 5001 or no fill error code.

**Comment by thomasmso** [comment]
If you are not receiving fill - it might be a configuration issue for which we can help diagnose if you enable and send over our SDK's [verbose logs](https://dash.applovin.com/documentation/mediation/flutter/getting-started/advanced-settings#enable-verbose-logging) while attempting to load an ad. It might also just be a lack of advertising demand, so you should add more networks to your integration, you can read more here (#4): https://support.applovin.com/hc/en-us/articles/17528914710413

**Comment by ycv005** [comment]
Hi @thomasmso , Here is the verbose log - [Link](https://docs.google.com/document/d/1Fw6iZWYdZy2bsl2FjtUqzb9-G7hCL2FlVSnf4jiO6vg/edit?usp=sharing)
Tested on Real device with usb debugging. Verbose was on and show debugger was enable.

**Comment by ycv005** [comment]
@thomasmso 
What else you have observe from above verbose.

Before AppLovin, we were using Google Admanager, we were seeing all kinds of ads and later on we thought to use app lovin, where integration to all network we found easy. So, right now with AppLovin, none of ads are visible nor self applovin or google admanager ads. Only Interestial ads from unity is visible. We are getting lot of request and we have confirm same in google admanager console. Atleast, single banner ads should be shown or single interstitial ads should be shown from other network.

So, here the current scenario
1 - Emulator/Test device - Test ads are visible (Banner, and Interstitial Ads are visible) (but no rewarded ads are visible)

2 - Play Store Live App - Ads are visible (Interstitial ads only are visible )  (but not banner, rewarded ads are visible)

3 - My SDK configuration are correct that's why Ads are visible from Unity mediation network. I have followed this flutter method - https://dash.applovin.com/documentation/mediation/flutter/getting-started/integration

Major Problem (High Priority)
4 - Why the Banner Ads are not visible inspite high ads request from our several users. We understand ad request demand need high request so we waited for few days, but it is more than 1 week. I have implemented the Banner Ads via Widget method.

<img width="357" alt="app_max" src="https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26734819/76eb5e9f-c4ee-4d6b-a70b-9e1a32f92ad3">

![WhatsApp Image 2023-07-31 at 21 59 15](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26734819/733eba87-4f01-4482-8019-1cd335299a21)

**Comment by thomasmso** [comment]
>1 - Emulator/Test device - Test ads are visible (Banner, and Interstitial Ads are visible) (but no rewarded ads are visible)

I just tested test iOS rewarded ads, and they load and show fine. If it is not working for you, I would have to request the logs again while you are attempting to load/show.

>2 - Play Store Live App - Ads are visible (Interstitial ads only are visible ) (but not banner, rewarded ads are visible)

Can you send the Play Store URL?

>Major Problem (High Priority)
>4 - Why the Banner Ads are not visible inspite high ads request from our several users. We understand ad request demand need high request so we waited for few days, but it is more than 1 week. I have implemented the Banner Ads via Widget method.

We will be able to investigate more once we get to test the live app

**Comment by ycv005** [comment]
if you can give me your email, I would add you ad internal tester to test production app with debug mode (I will make new internal release)

**Comment by ycv005** [comment]
@thomasmso 
I can't see any rewarded ads logs in android either on emulator or test device. By the way, I have some verbose share when testing rewarded ads - https://github.com/AppLovin/AppLovin-MAX-Flutter/issues/98#issuecomment-1660433479
[Play store link ](https://play.google.com/store/apps/details?id=com.topbestof.qwizb)

Also, please mail me your email at ycverma005@gmail.com, so that I could give you internal access to app so that you can debug live production with debugger enable.

**Comment by thomasmso** [comment]
In your logs, I don't see any requests for rewarded ads being made. Are you sure you are following our [docs](https://dash.applovin.com/documentation/mediation/flutter/ad-formats/rewarded-ads)? Do you have integration code surrounding your rewarded ads logic that you can share?

Can you add hiroshi.watanabe@applovin.com (cc @alhiwatan) to testing? I'll work with him behind-the-scenes on it.

**Comment by ycv005** [comment]
Here is an internal (34 version) - [Link](https://play.google.com/apps/internaltest/4701415554019576932)

Now, coming to reward ads, here is code as well as screenshot, showing my debugger to at reward ads (mean, my code is reachable, so reward ads logs should be visible)

Reward Ad Code
```
  void _createAppLovinRewardAd(BuildContext context) {
    var rewardedAdRetryAttempt = 0;
    String rewardedAdUnitId =
        context.read<SystemConfigCubit>().applovinRewardedAdId();
    AppLovinMAX.setRewardedAdListener(
      RewardedAdListener(onAdLoadedCallback: (ad) {
        // Rewarded ad is ready to be shown. AppLovinMAX.isRewardedAdReady(rewardedAdUnitId) will now return 'true'
        print('Rewarded ad loaded from ' + ad.networkName);
        emit(RewardedAdLoaded());
        // Reset retry attempt
        rewardedAdRetryAttempt = 0;
      }, onAdLoadFailedCallback: (adUnitId, error) {
        // Rewarded ad failed to load
        // We recommend retrying with exponentially higher delays up to a maximum delay (in this case 64 seconds)
        rewardedAdRetryAttempt = rewardedAdRetryAttempt + 1;

        emit(RewardedAdFailure());
        int retryDelay = pow(2, min(6, rewardedAdRetryAttempt)).toInt();
        print('Rewarded ad failed to load with code ' +
            error.code.toString() +
            ' - retrying in ' +
            retryDelay.toString() +
            's');

        Future.delayed(Duration(milliseconds: retryDelay * 1000), () {
          AppLovinMAX.loadRewardedAd(rewardedAdUnitId);
        });
      }, onAdDisplayedCallback: (ad) {
        print("here applovin onAdDisplayedCallback");
      }, onAdDisplayFailedCallback: (ad, error) {
        print("here applovin onAdDisplayFailedCallback $error");
        Future.delayed(const Duration(seconds: 2), () {
          AppLovinMAX.loadRewardedAd(rewardedAdUnitId);
        });
      }, onAdClickedCallback: (ad) {
        print("here applovin onAdDisplayFailedCallback");
      }, onAdHiddenCallback: (ad) {
        AppLovinMAX.loadRewardedAd(rewardedAdUnitId);
      }, onAdReceivedRewardCallback: (ad, reward) {
        _rewardUserAfterAdWatch(context);
        Future.delayed(const Duration(seconds: 2), () {
          AppLovinMAX.loadRewardedAd(rewardedAdUnitId);
        });
      }),
    );
  }

```
and here is Reward ad on show code

```
  void showAd({
    required BuildContext context,
  }) async {
    //if ads is enable
    var sysConfigCubit = context.read<SystemConfigCubit>();
    if (sysConfigCubit.isAdsEnable()) {
      if (state is RewardedAdLoaded) {
        //if google ad is enable
        var adsType = sysConfigCubit.adsType();
        if (adsType == 1) {
          // show google reward ads
        } else if (adsType == 4) {
          String rewardedAdUnitId =
              context.read<SystemConfigCubit>().applovinRewardedAdId();
          bool isReady =
              (await AppLovinMAX.isRewardedAdReady(rewardedAdUnitId))!;
          if (isReady) {
            AppLovinMAX.showRewardedAd(rewardedAdUnitId);
          }
        }  else {
          UnityAds.showVideoAd(
            placementId: unityRewardsPlacement(),
            onComplete: (placementId) {
              createRewardedAd(context);
            },
            onFailed: (placementId, error, message) =>
                print('Video Ad $placementId failed: $error $message'),
            onStart: (placementId) => print('Video Ad $placementId started'),
            onClick: (placementId) => print('Video Ad $placementId click'),
          );
        }
      } else if (state is RewardedAdFailure) {
        //create reward ad if ad is not loaded successfully
        createRewardedAd(context);
      }
    }
  }

```

<img width="621" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26734819/5a33f147-168e-4da0-af1c-aca132a6d6f4">

**Comment by thomasmso** [comment]
You need to make an explicit call to `AppLovinMAX.loadRewardedAd(rewardedAdUnitId);` to trigger the initial rewarded ad load.

**Comment by ycv005** [comment]
@thomasmso then the docs are not properly updated. Here I can only found loadedRewardedAd once even that is found inside failed ad 
<img width="812" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26734819/44832858-43e3-4a92-ac77-98f878976728">

**Comment by thomasmso** [comment]
@ycv005 - You're right. We've updated the [doc](https://dash.applovin.com/documentation/mediation/flutter/ad-formats/rewarded-ads) accordingly.

**Comment by ycv005** [comment]
@thomasmso can you make sure for banner ads via widget method, not to occupy space to fix in next release. I hope next release will be soon in 1-2 week  😬.

**Comment by thomasmso** [comment]
@ycv005 - Yes, @alhiwatan is currently investigating that change. We have to make sure any changes we make do not break existing integrations. And again, thanks for catching our docs error.

**Comment by thomasmso** [comment]
@ycv005 - We pushed Flutter plugin v3.1.0 which should resolve the issue.

cc @alhiwatan

**Comment by ycv005** [comment]
@thomasmso Thanks, I will check and update because, still i am not getting banner ads but i am getting interstitial and rewarded ads. Don't know why request are high.
