### ISSUE TITLE
Account banned after implementing 

### ISSUE THREAD

**Issue by laurentiu0** [AppLovin/AppLovin-MAX-Flutter#41]
### MAX Plugin Version

Lastes

### Flutter Version

Latest

### Device/Platform Info

-

### Current Behavior

After I've implemented the Flutter SDK my account got banned with the reason: check the TOS.

I've tried to contact the support team but they do not respond to my emails because I am banned.

My account is almost 2 y old and I never got anything like this one here.

Can you do something about it?

### How to Reproduce

-

**Comment by laurentiu0** [comment]
I've used the flutter sdk for almost 2months.

**Comment by thomasmso** [comment]
Can you screenshot the messaging you see on your UI?

**Comment by laurentiu0** [comment]
There is none, I can't login to my applovin account and the only message I get  is that the  id is not good and can't receive ads.

**Comment by laurentiu0** [comment]
Is there any chance I can recover my account? It was removed without prior notice.

**Comment by johnmollaghan** [comment]
Which account has been suspended? Your Apple account, Google, Applovin?

**Comment by laurentiu0** [comment]
AppLovin

> Which account has been suspended? Your Apple account, Google, Applovin?
