### ISSUE TITLE
Several crashes with rewarded ad on iOS

### ISSUE THREAD

**Issue by kreativityapps** [AppLovin/AppLovin-MAX-Flutter#44]
### MAX Plugin Version

2.0.0

### Flutter Version

3.0.5

### Device/Platform Info

iOS 15

### Current Behavior

Several crashes appear in Crashlytics and XCode logs.

> Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x99288 __exceptionPreprocess
1  libobjc.A.dylib                0x16744 objc_exception_throw
2  CoreFoundation                 0xf0390 __CFDictionaryCreateGeneric
3  Runner                         0x2e2eb4 +[MARewardedAd sharedWithAdUnitIdentifier:sdk:]
4  Runner                         0x1a8a98 -[AppLovinMAX retrieveRewardedAdForAdUnitIdentifier:] + 825 (AppLovinMAX.m:825)
5  Runner                         0x1a67f0 -[AppLovinMAX isRewardedAdReadyForAdUnitIdentifier:result:] + 413 (AppLovinMAX.m:413)
6  Runner                         0x1aba78 -[AppLovinMAX handleMethodCall:result:] + 1254 (AppLovinMAX.m:1254)
7  Flutter                        0x55ae50 (Missing UUID b5f419596300357c85f161f5e6e0920d)
8  Flutter                        0x42cd0 (Missing UUID b5f419596300357c85f161f5e6e0920d)
9  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release
10 libdispatch.dylib              0x3a30 _dispatch_client_callout
11 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain
12 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF
13 CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
14 CoreFoundation                 0xb704 __CFRunLoopRun
15 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific
16 GraphicsServices               0x1374 GSEventRunModal
17 UIKitCore                      0x514b58 -[UIApplication _run]
18 UIKitCore                      0x296090 UIApplicationMain
19 Runner                         0x590c main + 8 (AppDelegate.swift:8)
20 ???                            0x1065d9da4 (Missing)

### How to Reproduce

Can't reproduce. Seen only in crash logs, it must be related to rewarded ads.

**Comment by alhiwatan** [comment]
@kreativityapps , thanks for reporting.   Could you let us know a few things about the issue?

- What is the exception message when you have NSInvalidArgumentException?   There must be an error message along with it.
- What percentage of daily active users are affected by this issue?

**Comment by kreativityapps** [comment]
Hi @alhiwatan, thanks for getting back so quickly.

Exception message: 
> Fatal Exception: NSInvalidArgumentException
> No sdk specified

Almost 5% of users are affected. Ran an A/B test applovin enabled/disabled. 
Disabled -> 100% crash-free with 1000 users
Enabled -> 95% crash-free with 1000 users
Affects both iphone and ipads.

**Comment by thomasmso** [comment]
@alhiwatan - Looks like when [this LoC](https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/master/applovin_max/ios/Classes/AppLovinMAX.m#L825) is called, `self.sdk` is `nil`. Which might indicate 
 @kreativityapps is not creating the rewarded ad objects after our plugin is done initializing.

@kreativityapps - Could you provide code snippet of your integration surroudning our plugin's init + loading rewarded ads?

https://dash.applovin.com/documentation/mediation/flutter/getting-started/integration#initialize-the-sdk
https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/master/applovin_max/ios/Classes/AppLovinMAX.m#L136

**Comment by kreativityapps** [comment]
This is the code, let me know if more details are needed.
```int _rewardedAdRetryAttempt = 0;
await AppLovinMAX.initialize(Constants.applovinKey);
AppLovinMAX.createBanner(
  Constants.applovinIOSBanner,
  AdViewPosition.topCenter,
);
initializeRewardedAds();
AppLovinMAX.setVerboseLogging(kDebugMode);

void initializeRewardedAds() {
  AppLovinMAX.setRewardedAdListener(
    RewardedAdListener(
      onAdLoadedCallback: (ad) {
        _rewardedAdRetryAttempt = 0;
      },
      onAdLoadFailedCallback: (adUnitId, error) {
        _rewardedAdRetryAttempt = _rewardedAdRetryAttempt + 1;
        final int retryDelay =
            pow(2, min(6, _rewardedAdRetryAttempt)).toInt();
        Future.delayed(Duration(milliseconds: retryDelay * 1000), () {
          AppLovinMAX.loadRewardedAd(Constants.applovinIOSRewarded);
        });
      },
      onAdDisplayedCallback: (ad) {},
      onAdDisplayFailedCallback: (ad, error) {},
      onAdClickedCallback: (ad) {},
      onAdHiddenCallback: (ad) {},
      onAdReceivedRewardCallback: (ad, reward) {
        Future.delayed(const Duration(milliseconds: 1000), () {
          AppLovinMAX.loadRewardedAd(Constants.applovinIOSRewarded);
        });
      },
    ),
  );
  AppLovinMAX.loadRewardedAd(Constants.applovinIOSRewarded);
}

**Comment by kreativityapps** [comment]
For Flutter iOS setup is enough to use `await AppLovinMAX.initialize(applovinKey)`, right?
Or the key has to be added also to the Info.plist like described in the iOS documentation?
https://dash.applovin.com/documentation/mediation/ios/getting-started/integration#add-the-sdk-key

**Comment by kreativityapps** [comment]
Hi, the issue was with AppLovinMAX.isRewardedAdReady. 
In my code it was possible to execute it without initialising Applovin first. Missed this branch.
It's surrounded by a try - catch, on Android the error is handled, but on iOS the app crashes. This issue looks solved to me now, but maybe you want to look into the iOS crash. Thank you for your time.
