### ISSUE TITLE
Add support to Lock Screen Ads

### ISSUE THREAD

**Issue by ivanmr97** [AppLovin/AppLovin-MAX-Flutter#48]
### Feature Description

Is it possible to add support for these types of ads? I have seen that they are available in the android SDK, but not in the flutter plugin.

Thank you in advance!

**Comment by ivanmr97** [comment]
The application for which I want to use it, is not yet available, it is in the final phase of development, it is an app to play sports and listen to music. For this type of apps, an ad of this type would be perfect. That's why i want it. I'm sure there will be a lot of people who would love to have this feature available as there are few ad networks with this type of ad. @thomasmso

**Comment by thomasmso** [comment]
@ivanmr97 - We need to try our best to quantify the demand / users before investing engineering resources. Do let us know when it is launched and we can re-assess.

**Comment by adriancsbna** [comment]
It would be nice to have that option for ads

**Comment by thomasmso** [comment]
We just released v2.3.0 which has support for App Open ads. We don't have docs yet, but you can reference the code for API usage here: https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/55

**Comment by ivanmr97** [comment]
Hello! Im' glad to see that feature added in the plugin, but i requested the lockscreen ads haha not the app open ads, anyway thank you for adding this new feature, but also it would be nice if you can add the lockscreen ads too!

**Comment by thomasmso** [comment]
Hi @ivanmr97 - oh ok, that still isn't prioritized, but in the meantime the native Android SDK needs access to `ViewGroup`s in the lockscreen, we're not sure how this API should look like in Flutter.

**Comment by ivanmr97** [comment]
Any news about this? Are you planning to add LockScreen Ads in the future?

**Comment by thomasmso** [comment]
Not at the moment. Havn't received new requests in months.
