### ISSUE TITLE
dispose a loaded interstitial/rewarded

### ISSUE THREAD

**Issue by uditrugman** [AppLovin/AppLovin-MAX-Flutter#49]
### Feature Description

is there a way to dispose a loaded interstitial/rewarded ad?

Motivation:
during Application start, I initiate a preload request for multiple ad-units. 
each ad-unit has a different floor eCPM.
after each load-completion, I'd like to keep only the ad with the highest eCPM.

for that I need to dispose previous loaded ads.

thanks

**Comment by thomasmso** [comment]
This is not a feature MAX supports - we're the platform that is responsible for the auction dynamics and the ads that will be loaded and shown to the users.

**Comment by uditrugman** [comment]
should i at all, preload an ad during application start to ensure that it's ready when needed?

**Comment by thomasmso** [comment]
Yes, we [recommend](https://dash.applovin.com/documentation/mediation/flutter/getting-started/integration#initialize-the-sdk) you to preload ads after our plugin is initialized.

**Comment by uditrugman** [comment]
and is there a TTL for a loaded interstitial?  
how much memory / bandwidth a loaded interstitial consume?

**Comment by thomasmso** [comment]
Both of those characteristics are highly variable for every mediated network

**Comment by uditrugman** [comment]
so if there is a TTL for a loaded interstitial, how can I preload an ad and can't know the expiration time of that ad?

1.  let's say a user opens the app
2.  a preload is initiated
3.  now more than TTL minutes can pass until the ad is shown

shouldn't I have control over this?

am I missing something?

**Comment by thomasmso** [comment]
Our plugin will automatically reload an expired ad under-the-hood.

**Comment by Nero-2333** [comment]
Hi @uditrugman, did you solve this problem?
