### ISSUE TITLE
Add support for godot game engine 

### ISSUE THREAD

**Issue by ghost** [AppLovin/AppLovin-MAX-Flutter#5]
Please make applovin max available for godot game engine.

**Comment by thomasmso** [comment]
@hani09876 - Can you send us your portfolio so we can assess the opportunity?

**Comment by hani09876** [comment]
> @hani09876 - Can you send us your portfolio so we can assess the opportunity?

Sir, I don't have any portfolio. But i have games available on play store. And i want to use applovin max on my game. I am using godot game engine for making my game. 


There are more game developers who want to use applovin max on there game . Currently we are using a 3rd party plugin to use applovin max. And the plugin isn't working well. This is horrible for every game developer. Currently we are using this plugin
https://github.com/DrMoriarty/nativelib


You can check there website here 
https://godotengine.org/

Most of the youtuber think godot  is in the 2nd position of all game engine. So i think applovin max should have a support for using there ads on Godot. Please do this. Sir

**Comment by thomasmso** [comment]
Thanks, by portfolio, I meant your Play Store URL. We can only assess the opportunity with that. You can email it to thomas.so@applovin.com if you'd like.

**Comment by hani09876** [comment]
> Thanks, by portfolio, I meant your Play Store URL. We can only assess the opportunity with that. You can email it to thomas.so@applovin.com if you'd like.

Sir,I don't have to many install on my game right now. Here is my store link. But i think you shouldn't judge my games by counting install.. please consider my proposal and make a support for godot 


https://play.google.com/store/apps/dev?id=4705839298507600506

**Comment by thomasmso** [comment]
Thank you. We will likely not be able to get to this project until there is more demand from the community.

**Comment by thomasmso** [comment]
https://dash.applovin.com/documentation/mediation/godot/getting-started/integration
