### ISSUE TITLE
E/FrameEvents(17819): updateAcquireFence: Did not find frame.

### ISSUE THREAD

**Issue by Omi231** [AppLovin/AppLovin-MAX-Flutter#50]
### MAX Plugin Version

2.0.0

### Flutter Version

3.3.0-0.5.pre

### Device/Platform Info

Android 12

### Current Behavior

Showing a banner ad by widget method gives weird log which constantly keeps printing indefinitely. Removing the banner ad and hot reloading immediately stops the log. 
`E/FrameEvents(17819): updateAcquireFence: Did not find frame.`

Screenshot:
![image](https://user-images.githubusercontent.com/44071105/193686802-d6008a2d-2172-42f3-8d87-34be90c0a331.png)

### Expected Behavior

no unwanted log

### How to Reproduce

`MaxAdView(
  adUnitId: _bannerAdunitId,
  adFormat: AdFormat.banner
),`

Just show banner this way and log goes buzzerk. 

### Additional Info

Even created new fresh project and it still produces this behavior.

**Comment by alhiwatan** [comment]
Could you enable [verbose logging](https://dash.applovin.com/documentation/mediation/flutter/getting-started/advanced-settings#enable-verbose-logging) and upload the logs here?

**Comment by Omi231** [comment]
@alhiwatan here is the log.
[log.txt](https://github.com/AppLovin/AppLovin-MAX-Flutter/files/9725155/log.txt)

**Comment by alhiwatan** [comment]
Thanks for the logs.   It seems that this is a popular flutter issue.   Probably, you've already searched for it and found [this](https://github.com/flutter/flutter/issues/104268).

I agree that this is annoying.   I can see the same message repeatedly in our demo app until the banner/mrec is closed.

But, according to [that information](https://github.com/flutter/flutter/issues/104268), this is not particularly harmful and can be ignored.   Let's monitor the Android/flutter update.

**Comment by shinriyo** [comment]
flutter_webview in Android
it is annoying...

**Comment by rafay99-epic** [comment]
> flutter_webview in Android it is annoying...

   
I know, but I have to use it in a Flutter project, and I am getting these missing frame errors:

![image](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/82662797/b69e43a7-f7f3-4dcd-8ce0-1fdd93ce91f1)

The application on the home screen is so lagging, and I don't understand why. Any suggestions?

**Comment by urban-hostel** [comment]
Please fix becouse running 
`flutter run 2>&1 | Where-Object { $_ -notmatch "updateAcquireFence: Did not find frame." }`

is not a long term solution to debug other issues

![image](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/144593370/4ee628fe-a73f-498b-b5d5-fca47ccc1f13)

**Comment by alhiwatan** [comment]
Closing this issue out due to inactivity.  It seems that the error is gone with Flutter 3.16.2.

**Comment by onimeshc-iprogrammer** [comment]
This issue still persists in 3.16

**Comment by harshans22** [comment]
it is still in flutter 3.19
