### ISSUE TITLE
can't close ads on tvbox

### ISSUE THREAD

**Issue by willsalasare** [AppLovin/AppLovin-MAX-Flutter#52]
### MAX Plugin Version

2.2.0

### Flutter Version

3.3.5

### Device/Platform Info

Android TV

### Current Behavior

ads cannot be closed with tvbox control

### Expected Behavior

Close ads by pressing "x" with tv box control

### How to Reproduce

1. Show ads
2. Finish
3. Could not close

**Comment by alhiwatan** [comment]
@willsalasare, thanks for reporting the issue.   Currently, we do not support Android TV.   How crucial is it not working for your project?    Would it be helpful if the `back` press in the tv control worked?

**Comment by willsalasare** [comment]
I only do tests, it is the only problem that there is, it does not select the "x" with the control, yes, it would be useful if it were closed with the back button of the control

**Comment by alhiwatan** [comment]
@willsalasare, thanks for your input.   Again, we currently do not support Android TV, so will leave this open for a while as a reference.
