### ISSUE TITLE
Update fails!

### ISSUE THREAD

**Issue by leon6003** [AppLovin/AppLovin-MAX-Flutter#53]
### MAX Plugin Version

2.2.0

### Flutter Version

latest

### Device/Platform Info

Androoid

### Current Behavior

After update to version 2.2.0
I get this error. Please help!

unning Gradle task 'assembleRelease'...                        
Picked up _JAVA_OPTIONS: -Xmx2012M

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processReleaseResources'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.applovin:applovin-sdk:+.
     Required by:
         project :app
      > Failed to list versions for com.applovin:applovin-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/applovin/applovin-sdk/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/applovin/applovin-sdk/maven-metadata.xml'.
               > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 

### How to Reproduce

n/a

**Comment by ri938** [comment]
I am also having this issue.  Bintray is down and since its a deprecated service its not clear when it will come back.  Its better to move away from using this.

**Comment by ri938** [comment]
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.applovin:applovin-sdk:+.
     Required by:
         project :app
      > Failed to list versions for com.applovin:applovin-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/applovin/applovin-sdk/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/applovin/applovin-sdk/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/applovin/applovin-sdk/maven-metadata.xml'.
                  > Read timed out

**Comment by leon6003** [comment]
Hi Ri938,

what do you mean with "move away from using this." ? 
Bintray or the plugin ? If you mean bintray how can this be done?

**Comment by ri938** [comment]
I mean that I think the applovin-sdk depends on jcenter and so the developers of applovin should migrate away from this.  I dont think we can do this as users? But I am no sure on this.

**Comment by santoshbagadi** [comment]
Hi @ri938 , AppLovin SDK or adapters are not hosted on Jcenter. Our SDKs are hosted on `mavenCenteral()`. As recommended in our docs here, please add `mavenCentral()` to your repositories block and remove any references to `jcenter()`.
