### ISSUE TITLE
[AppLovinSdk] Current SDK version (11.5.5) is outdated. Please integrate the latest version of the AppLovin SDK (11.6.0). Doing so will improve your CPMs and ensure you have access to the latest revenue earning features.

### ISSUE THREAD

**Issue by wadychou** [AppLovin/AppLovin-MAX-Flutter#61]
### Feature Description

applovin_max: ^2.3.1

[AppLovinSdk] Current SDK version (11.5.5) is outdated. Please integrate the latest version of the AppLovin SDK (11.6.0). Doing so will improve your CPMs and ensure you have access to the latest revenue earning features.

How to integrate the latest version of the AppLovin SDK (11.6.0)??

**Comment by thomasmso** [comment]
Live in v2.3.2.
