### ISSUE TITLE
onAdLoadFailedCallback not called when ad failed to load

### ISSUE THREAD

**Issue by hoalt** [AppLovin/AppLovin-MAX-Flutter#62]
### MAX Plugin Version

2.3.2

### Flutter Version

2.18.5

### Device/Platform Info

Android 6.0, Galaxy S6

### Current Behavior

No ad showing and onAdLoadFailedCallback not called. So I can't hide the space the ads take up.

### Expected Behavior

onAdLoadFailedCallback is called when ad failed to load

### How to Reproduce

Step 1: Turn off internet connection
Step 2: Open the screen with ads

**Comment by hoalt** [comment]
Additional: I use MaxAdView for my screen
MaxAdView(
        adUnitId: bannerAdUnitId,
        adFormat: AdFormat.banner,
        listener: AdViewAdListener(onAdLoadedCallback: (ad) {
          log('Banner widget ad loaded from ${ad.networkName}');
        }, onAdLoadFailedCallback: (adUnitId, error) {
          log('Banner widget ad failed to load with error code ${error.code} and message: ${error.message}');
        }, onAdClickedCallback: (ad) {
          log('Banner widget ad clicked');
        }, onAdExpandedCallback: (ad) {
          log('Banner widget ad expanded');
        }, onAdCollapsedCallback: (ad) {
          log('Banner widget ad collapsed');
        }, onAdRevenuePaidCallback: (ad) {
          log('Banner widget ad revenue paid: $ad.revenue');
        }));

**Comment by hoalt** [comment]
Additional: I'm using MaxAdView for my screens
`MaxAdView(
        adUnitId: bannerAdUnitId,
        adFormat: AdFormat.banner,
        listener: AdViewAdListener(onAdLoadedCallback: (ad) {
          log('Banner widget ad loaded from ${ad.networkName}');
        }, onAdLoadFailedCallback: (adUnitId, error) {
          log('Banner widget ad failed to load with error code ${error.code} and message: ${error.message}');
        }, onAdClickedCallback: (ad) {
          log('Banner widget ad clicked');
        }, onAdExpandedCallback: (ad) {
          log('Banner widget ad expanded');
        }, onAdCollapsedCallback: (ad) {
          log('Banner widget ad collapsed');
        }, onAdRevenuePaidCallback: (ad) {
          log('Banner widget ad revenue paid: $ad.revenue');
        }))`

**Comment by thomasmso** [comment]
@hoalt - Can you check if you leave the device by itself for 1-2 minutes to see if the callback eventually fires?

**Comment by anandyadav21219** [comment]
Not working @thomasmso

**Comment by thomasmso** [comment]
@anandyadav21219 - Could you enable and send over our plugin's verbose logs? 

https://dash.applovin.com/documentation/mediation/flutter/getting-started/advanced-settings#enable-verbose-logging

**Comment by amondnet** [comment]
@thomasmso @hoalt 

MaxAdView uses its own [method channel](https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/d2223c7579442c8453f5defab875a500da9c84b4/applovin_max/lib/src/max_ad_view.dart#L135). Error events should also be passed through that method channel. Currently, we cannot receive the `OnAdViewAdLoadFailedEvent` because it uses the shared method channel('applovin_max') to pass error events.

https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/d2223c7579442c8453f5defab875a500da9c84b4/applovin_max/android/src/main/java/com/applovin/applovin_max/AppLovinMAX.java#L800

see #82

**Comment by thomasmso** [comment]
PR: https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/89

**Comment by thomasmso** [comment]
Fixed in v2.5.0
