### ISSUE TITLE
SemVer rules failed for 2.3.2

### ISSUE THREAD

**Issue by al-tush** [AppLovin/AppLovin-MAX-Flutter#64]
### MAX Plugin Version

2.3.2

### Flutter Version

3.3.8

### Device/Platform Info

Any

### Current Behavior

Update from 2.3.1 to 2.3.2 needs to update code which depends from 
```
  /// The ad’s revenue amount, or 0 if no revenue amount exists.
  final String revenue;
```

It is not ok https://dart.dev/tools/pub/versioning#semantic-versions

### How to Reproduce

Update from 2.3.1 to 2.3.2 breaks existing code

**Comment by alhiwatan** [comment]
@al-tush, thanks for reporting the issue, and we apologize for any inconvenience this may have caused.   Since the plugin is still pretty new, there are many iterations, and we don’t want to bump the major version all the time.

**Comment by al-tush** [comment]
Pretty new == less than 1.0.
It is very important to follow SemVer rules. Otherwise a lot of projects will be broken.

**Comment by thomasmso** [comment]
@al-tush - The plugin is < 6 months old, with some changes in between that warranted a major version bump. But it is fair to not break semantic versioning rules no matter how big or small the breaking change(s) are. We'll note that going forward, and we thank you for raising this concern with us.
