### ISSUE TITLE
 _interstitialRetryAttempt  is only reset if an ad is shown. 

### ISSUE THREAD

**Issue by leon6003** [AppLovin/AppLovin-MAX-Flutter#66]
### MAX Plugin Version

2.3.1

### Flutter Version

2.18.5

### Device/Platform Info

virtual

### Current Behavior

Hi,

the _interstitialRetryAttempt  is only reset if the ad is shown. 
Is this correct?

### Expected Behavior

I would expect _interstitialRetryAttempt  to be reset in onAdLoadFailedCallback when it fails to load after 6 attempts.

### How to Reproduce

Code review

**Comment by alhiwatan** [comment]
@leon6003, this will be an issue with our demo app.    We'll fix it when we have a chance.
