### ISSUE TITLE
Missing  interstitialLoadState set to AdLoadState.loading ?

### ISSUE THREAD

**Issue by leon6003** [AppLovin/AppLovin-MAX-Flutter#69]
### MAX Plugin Version

2.3.2

### Flutter Version

latest

### Device/Platform Info

Android

### Current Behavior

In ElevatedButton(...) function  the interstitialLoadState is set to AdLoadState.loading after a new ad is loaded
but in the onAdLoadFailedCallback: the interstitialLoadState is set to AdLoadState.Notloaded and this is kept even after loading a new ad is this callback function.

To me this means that Elevated button will show "Load Interstitial" even if a loading is ongoing.

I am not sure if this is an problem but I read that one should not load extra ads before they are shown or failed.

What is correct?

### How to Reproduce

Code review

**Comment by alhiwatan** [comment]
@leon6003, thanks for reporting.   When the load fails, `AdLoadState.notLoaded` is set, then the demo app will retry the load after a few seconds.   At the time, the demo app currently does not update the status, so the button still shows "Load Interstitial".

We will update our demo app when we have a chance.
