### ISSUE TITLE
custom pre ATT dialog

### ISSUE THREAD

**Issue by daniel-hopkins** [AppLovin/AppLovin-MAX-Flutter#72]
### Feature Description

Any chance we can 
A. customize the Applovin _pre_ ATT dialog?
or
B. disable it's use so that we can use our own?

I had already created my own that matched the design of my app, but disabled it once I installed AppLovin.
Same request for the Swift version of the plugin. I can make the request there too if needed.

Thanks!!

**Comment by thomasmso** [comment]
Hey - we're actually deprecating that flow completely and will be removed in a future SDK Release. You can disable it by reversing the [steps you performed to enabled it](https://dash.applovin.com/documentation/mediation/flutter/getting-started/consent-flow).

**Comment by daniel-hopkins** [comment]
Super! So with that reversal, the Applovin SDK will just read / respect the ATT selection after rolling our own?

**Comment by thomasmso** [comment]
Correct - AppLovin and all mediated SDKs you have integrated will automatically read the latest ATT value from the OS.
