### ISSUE TITLE
App Crashing If We don't pass CustomData

### ISSUE THREAD

**Issue by mhanzla80** [AppLovin/AppLovin-MAX-Flutter#80]
### MAX Plugin Version

2.4.3

### Flutter Version

^3.7.0

### Device/Platform Info

iOS

### Current Behavior

When we don't pass custom data banner ad crash the app.

### Expected Behavior

Banner should be create

### How to Reproduce

Don't Pass custom data to banner Max ad view in iOS Platform.

**Comment by pvddeveloper** [comment]
same :(

**Comment by thomasmso** [comment]
Fixed in v2.4.4

**Comment by thomasmso** [comment]
https://github.com/AppLovin/AppLovin-MAX-Flutter/releases/tag/release_2_4_4
