### ISSUE TITLE
BannerExtraParameter adaptive_banner = false not work

### ISSUE THREAD

**Issue by pvddeveloper** [AppLovin/AppLovin-MAX-Flutter#81]
### MAX Plugin Version

2.4.4

### Flutter Version

3.7.5

### Device/Platform Info

iOS

### Current Behavior

When AppLovinMAX.setBannerExtraParameter(bannerAdUnitId, "adaptive_banner", "false");

### Expected Behavior

Sometime return admob adaptive banner => can't show banner => white widget

### How to Reproduce

Not return adaptive banner when setBannerExtraParameter key = adaptive_banner and value = false

**Comment by thomasmso** [comment]
@pvddeveloper - Could you enable and send over our plugin's [verbose logs](https://dash.applovin.com/documentation/mediation/flutter/getting-started/advanced-settings#enable-verbose-logging)? And perhaps a recording of the "white widget'?

**Comment by ycv005** [comment]
@thomasmso Does below is the right way to get adaptive banner ads via Widget method. Also, what is difference between customData and extraParameters. The applovin's doc is bit confusing. Since, customData accept string, so I am passing userId while applovin's programtic way of displaying banner shows to pass adaptive_banner. `Please make clear here.`

```
  MaxAdView? _createAppLovinBannerAd() {
    String adUnit = context
        .read<SystemConfigCubit>()
        .applovinBannerId(bannerType: _bannerSize!);
    if (adUnit.isEmpty) {
      return null;
    }
    Map<String, String>? extraParameters = {
      "adaptive_banner": "true",
    };
    return MaxAdView(
      adUnitId: adUnit,
      visible: false,
      isAutoRefreshEnabled: true,
      customData: context.read<UserDetailsCubit>().userId(),
      extraParameters: extraParameters,
      adFormat: CustomBannerSize.large == _bannerSize
          ? AdFormat.mrec
          : AdFormat.banner,
      listener: AdViewAdListener(
          onAdLoadedCallback: (ad) {},
          onAdLoadFailedCallback: (adUnitId, error) {},
          onAdClickedCallback: (ad) {},
          onAdExpandedCallback: (ad) {},
          onAdCollapsedCallback: (ad) {}),
    );
  }

```

**Comment by ycv005** [comment]
@thomasmso Also, I found that you have update AppLovin Android SDK ([LINK](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/master/GoogleAdManager/CHANGELOG.md#22201)) following AdMob's adaptive nature.

Does, it or Admanager's adaptive ([LINK](https://developers.google.com/ad-manager/mobile-ads-sdk/flutter/banner)) compatible with new flutter's applovin sdk ? I am looking for both banner normal (320x50) and MREC (320x250). 
I can see below doc.
![WhatsApp Image 2023-08-24 at 19 44 17](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26734819/415adbe6-8820-49ef-bbac-fd7993ad6053)

**Comment by ycv005** [comment]
@thomasmso @alhiwatan , Need help with adaptive banner. The documentation is not clear. Widget method to use banner as adaptive is not mention. Please check my above comment.

**Comment by ycv005** [comment]
@thomasmso Our team has found that, after passing  "adaptive_banner": "true" as mentioned in above in widget method. The google ads close button was hidden. This is against their policy & will harm the ads.  Please help here ugrently @thomasmso  @alhiwatan 
<img width="477" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26734819/a233a62f-ca01-42ec-a648-58bfa45087b4">

**Comment by alhiwatan** [comment]
Your usage for setting an extra parameter in the AdVIew widget looks good.   Extra parameters are for customizing the SDK, and [customData](https://dash.applovin.com/documentation/mediation/reporting-api/user-ad-revenue#custom-data) is for tagging your ads.

For your issue about the hidden close button, you need to set the height for your adaptive banner with `AppLovinMAX.getAdaptiveBannerHeightForWidth()`.   But the function is missing (#117), which will be available soon.

**Comment by alhiwatan** [comment]
@ycv005, we have released the fix in [3.2.0](https://github.com/AppLovin/AppLovin-MAX-Flutter/releases/tag/release_3_2_0).

The MaxAdView widget is designed to size itself on its own.  The height will be calculated for adaptive banners with the newly added `adaptiveBannerWidth` property with the existing `extraParameters` property.

```
            MaxAdView(
                adUnitId: _bannerAdUnitId,
                adFormat: AdFormat.banner,
                adaptiveBannerWidth: ui.window.physicalSize.width,
                extraParameters: {"adaptive_banner":"true"},
```

The banner's height can also be retrieved by `AppLovinMAX.getAdaptiveBannerHeightForWidth()`, which works for both programmatic and native (widget) methods.

**Comment by ycv005** [comment]
Thanks for efforts and answering as well.

Also, can you help me in finding out tagged data in dashboard? I can't find out. Even, i open your provided link.

**Comment by ycv005** [comment]
@alhiwatan @thomasmso Still sometimes(not everytime), close button getting cut.

**Comment by alhiwatan** [comment]
Ok, let me check what we can do.

Btw, regarding `customData`, you can get it from the [User Revenue API](https://dash.applovin.com/documentation/mediation/reporting-api/user-ad-revenue#user-revenue-api) response.   But I'd recommend [Ad Placements](https://support.applovin.com/hc/en-us/articles/13886453860237-Advanced-Settings) if you want to see it in the dashboard.    You can filter Advance Reporting in the dashboard with your `Ad Placement`.

**Comment by alhiwatan** [comment]
@ycv005, you need to specify a slightly larger size for now.
