### ISSUE TITLE
The banner ad refreshes in the backstack

### ISSUE THREAD

**Issue by amondnet** [AppLovin/AppLovin-MAX-Flutter#87]
### MAX Plugin Version

2.4.6

### Flutter Version

3.7.7

### Device/Platform Info

iOS 16.1

### Current Behavior

The banner ad refreshes in the backstack when you navigate from one screen to another. A banner ad is on the home page of my app. When I navigate to another page (for example, the settings page), spend some time there (2-3 minutes), and then return to the home page, the banner ad refreshes. I noticed that the banner ad refreshes.
Is this correct behavior?

If I don't see an ad, can I keep refreshing the ad or should I stop refreshing?
In my service, I'm using [visibility_detector](https://pub.dev/packages/visibility_detector) to perform `stopAutoRefresh()`. 

### How to Reproduce

1. load banner ad ( screen A )
2. navigate to screen B ( screen B )
3. wait
4. The ad on screen A is refreshed ( screen B )

**Comment by thomasmso** [comment]
When the banner or MREC is not visible, you should stop autorefresh, resuming only when it is visible again.
