### ISSUE TITLE
AppLovin-MAX-Flutter plugin doesn't have the ability to display native ads

### ISSUE THREAD

**Issue by Yibei-ayuo** [AppLovin/AppLovin-MAX-Flutter#88]
### Feature Description

Right now, the AppLovin-MAX-Flutter plugin doesn't have the ability to display native ads. Is this a problem, or can we add this feature by using the Android version of the MAX SDK on our own?

**Comment by thomasmso** [comment]
Hi @Yibei-ayuo - we already have a thread to gauge demand for native ads here: https://github.com/AppLovin/AppLovin-MAX-Flutter/issues/26

If you'd like, you can integrate native ads via our native SDKs.
