### ISSUE TITLE
Unsafe Encryption & Implicit PendingIntent errors in Play Console

### ISSUE THREAD

**Issue by gkovac42** [AppLovin/AppLovin-MAX-Flutter#90]
Lately I'm seeing these two errors in the Play Console of my flutter app. I'm not exactly sure why, but this plugin is the only one that uses any kind of networking within the app. Has anyone had a similar experience?

Unsafe Encryption

Your app contains unsafe cryptographic encryption patterns. Please see [this Google Help Center article](https://support.google.com/faqs/answer/9450925) for details.

    bjqm.c (in dynamically loaded code)
    bjqm.d (in dynamically loaded code)

Implicit PendingIntent

Your app contains an Implicit PendingIntent vulnerability. Please see [this Google Help Center article](https://support.google.com/faqs/answer/10437428) for details.

    bpce.b (in dynamically loaded code)

**Comment by gkovac42** [comment]
My bad, it turned out to be another plugin. Closing.

**Comment by noxo** [comment]
@gkovac42 how did you resolve it, would be helpful in https://stackoverflow.com/questions/76101637/your-app-contains-unsafe-cryptographic-encryption-patterns-in-dynamically-loade

**Comment by gkovac42** [comment]
Hi, for me it was caused by aes_crypt plugin. It's rather outdated and not
really supported anymore so I just went with another solution.

**Comment by noxo** [comment]
> Hi, for me it was caused by aes_crypt plugin. It's rather outdated and not really supported anymore so I just went with another solution.

Thanks, I see [aes_crypt](https://github.com/alexgoussev/aes_crypt) could cause Unsafe Encryption "Unsafe Encryption", if used with static iv/key/ECB. I guess "Implicit PendingIntent" was fixed by updating some other dep.
