### ISSUE TITLE
Reward Ad S2S Callback event token is incorrect

### ISSUE THREAD

**Issue by andj207** [AppLovin/AppLovin-MAX-Flutter#91]
### MAX Plugin Version

applovin_max: ^2.5.0

### Flutter Version

Flutter 3.7.12

### Device/Platform Info

Android, IOS

### Current Behavior

The Applovin server sends a request with the {EVENT_TOKEN} macro is incorrect with what the document described.

The callback url of the Rewarded Ad unit in MAX:
`https://myserver.com/verifyreward?event={EVENT_ID}&token={EVENT_TOKEN}&amount={AMOUNT}&user_id={USER_ID}&data={CUSTOM_DATA}`

My debug log the request query parameters: 
`event=a46bd0fe2b866b797f7cea5babb16e2b4be968e6&token=8f0fcabd9e6e5af0b19896e367da7026198ae6bd&amount=3000.000000&user_id=yDvGtR6HXWaPMa7n0DBxSVefTpC3&data=mycustomdata`

As the doc on how the callback works (https://support.applovin.com/hc/en-us/articles/4403788356749-How-Server-to-Server-Callback-Works), I calculate the sha1 hash using node as below:

    const eventId = req.query.event;
    const eventToken = req.query.token;

    const shasum = crypto.createHash("sha1");
    const eventKey = <get key from environment var>; 
    // I can confirm the log event key is correct match with what show in the MAX reward ad unit
    
    const message = eventId + eventKey; // eventId get from the query parameter
    shasum.update(message);
    const resultToken = shasum.digest("hex"); 

The resultToken log is `8d36cba210a030e43e3ffa0573055aa08328999b` and not match with the eventToken in the query parametter.

I have double checked my code with the result built with sha1(eventId + eventKey) on http://www.sha1-online.com/ and they generate same sha1 hash result.

I don't know what sha1 function the Applovin using to calculate the hash that cause the different or my sha1 function missing some thing.

### Expected Behavior

eventToken in the query parameter match with my sha1 calculation.

### How to Reproduce

- Enable S2S callback, and ask support to generate event key for the account
- Setup server code like above
- Test with real reward ad

**Comment by thomasmso** [comment]
@andj207 - Since we'll need your account info to debug, could you send this inquiry to https://applovin.zendesk.com/hc/en-us/requests/new?

**Comment by andj207** [comment]
Thank you, @thomasmso ! I have sent the inquiry as advised.

**Comment by andj207** [comment]
The supporter told me to use the event key under Dashboard --> Account --> Keys instead of the one under the rewarded ad unit (the two are different). It is working perfectly now.
