### ISSUE TITLE
 [AppLovinSdk] ERROR [ALIncentivizedInterstitialAd] NOTE the above error might be due to linking issues with the iOS SDK, causing duplicate classes

### ISSUE THREAD

**Issue by ji-hyun219** [AppLovin/AppLovin-MAX-Flutter#92]
### MAX Plugin Version

2.4.6

### Flutter Version

3.7.12

### Device/Platform Info

iOS

### Current Behavior

Hello,
I am a Flutter beginner developer and I am using the Applovin Max plugin in my app. So far, there have been no problems, but an issue arose when I tried to add a framework made by another company. 

![스크린샷 2023-05-13 오후 2 47 57](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/91349474/a5dfcec3-135c-490e-a61c-f2fdf6123e5d)

This company is also using the Applovin SDK. It works fine on Android, but I am having trouble on iOS. The error message that I am receiving is as follows:

[AppLovinSdk] ERROR [ALIncentivizedInterstitialAd] NOTE the above error might be due to linking issues with the iOS SDK, causing duplicate classes

This is how my podfile is currently set up in the Flutter project:

```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  pod 'AppLovinSDK'                   
  pod 'AppLovinMediationInMobiAdapter' 
  pod 'AppLovinMediationTapjoyAdapter' 
end
```

The other company requested that I add the following to the podfile:

```
pod 'AdPopcornSSP', '2.4.2'
pod 'UnityAds', '4.2.1'
```

When I inquired about how they manage the Applovin SDK, they replied with the following:

"The AppLovin SDK inside is also managed by pod. We have the adapter files (.h, .m)."

This is the current situation, but I am not sure what the error message means exactly. Can you provide me with some insight on this issue?

### Expected Behavior

We hope that both our AppLovin SDK and the AppLovin SDK provided by the company will work properly.

### How to Reproduce

Here's the current Podfile:

```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  pod 'AppLovinSDK'                   
  pod 'AppLovinMediationInMobiAdapter' 
  pod 'AppLovinMediationTapjoyAdapter' 

  pod 'AdPopcornSSP', '2.4.2'
  pod 'UnityAds', '4.2.1'
end
```

And in our app's loading page, we're initializing it like this:

```
await AppLovinMAX.initialize(***********);
```

We're originally initializing our AppLovin SDK with our own AppLovin SDK key, and we've put the AppLovin SDK key given by another vendor in a separate info.plist file. Even when we tried using one of the keys to avoid any key duplication issues, the problem remains the same.

We've asked the vendor about this, but it seems like they don't know how to solve it either. Since I'm not familiar with iOS development, I'm not sure how to solve this either.

Is there anyone who can help? Thank you.

### Additional Info

We built with the same version of the AppLovin SDK for both SDKs.

**Comment by thomasmso** [comment]
Hi @ji-hyun219 - could you try removing `use_frameworks!` from your Podfile? 

>We're originally initializing our AppLovin SDK with our own AppLovin SDK key, and we've put the AppLovin SDK key given by another vendor in a separate info.plist file. Even when we tried using one of the keys to avoid any key duplication issues, the problem remains the same.
You should only use your own SDK key, and this AppLovin MAX plugin should be your primary SSP / mediation provider. If you have another SSP (Ad Popcorn?) mediating AppLovin demand, you shouldn't be using this plugin, and it is their responsibility to support you with the integration.

**Comment by ji-hyun219** [comment]
@thomasmso - I tried what you suggested, but I'm still experiencing the same error. 😭
Thank you for your response regarding the SSP as well.

**Comment by thomasmso** [comment]
@ji-hyun219 - Are you sure you updated the pods after removing `use_frameworks!` via `pod install --repo-update`?

**Comment by ji-hyun219** [comment]
@thomasmso
Hello,

Even if I remove only `use_frameworks!` within `target 'Runner' do` and run `pod install --repo-update`, the same issue still occurs.

So I also tried removing the `use_frameworks!` statement outside of the `target 'Runner' do` code block, thinking that it might have an impact, but other errors are still occurring.

Would it be okay for me to show you my code, even though it's a bit long?

As a reference, I commented out all `use_frameworks!` in the code below. (Note that `use_frameworks!` is used a total of three times)


```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

source 'https://github.com/CocoaPods/Specs.git'

# use_frameworks!
inhibit_all_warnings!


target 'Runner' do
  # use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # pod 'AdPopcornSSP', '2.4.2'
  # pod 'UnityAds', '4.2.1'

  pod 'AppLovinSDK'                     
  pod 'AppLovinMediationInMobiAdapter'  
  pod 'AppLovinMediationTapjoyAdapter'  
 

  pod 'NStationOfferwall', '1.0.2'
  pod 'GoogleUtilities'
  

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |build_configuration|
      build_configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'
    end
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_SENSORS=1',   
      ]
    end
  end
end

target 'ImageNotification' do
  # use_frameworks!
  pod 'Firebase/Messaging'
  pod 'GoogleUtilities'
end
```

I made the above changes to the code and ran `pod install --repo-update`, but another error appears.
I have attached an image of the error below :

![스크린샷 2023-05-15 오전 11 46 48](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/91349474/004ab458-921c-44a4-b0bf-b92b162ba439)

I have a question regarding the `use_frameworks!` statement. Is it your intention to remove all occurrences of this statement, not just those inside the `target 'Runner' do` block?

Thank you for your help.

**Comment by thomasmso** [comment]
Can you try adding the following only once at the top of your Podfile on top of `target 'Runner' do`?

```
use_frameworks!
inhibit_all_warnings!
```

then remove all other instances of either of those two lines and run `pod install`. That worked for me.

**Comment by ji-hyun219** [comment]
I called the `use_frameworks!` statement at the very top of the Podfile as you suggested, but I am still experiencing the same error([AppLovinSdk] ERROR [ALIncentivizedInterstitialAd] NOTE the above error might be due to linking issues with the iOS SDK, causing duplicate classes). 🥲

**Comment by ji-hyun219** [comment]
I called the `use_frameworks!` statement at the very top of the Podfile as you suggested, but I am still experiencing the same error([AppLovinSdk] ERROR [ALIncentivizedInterstitialAd] NOTE the above error might be due to linking issues with the iOS SDK, causing duplicate classes).

I have also executed `pod install`. 🥲

**Comment by ji-hyun219** [comment]
Hello @harryarakkal 
The Embed Frameworks is a framework provided by the another company. Due to security reasons, I don't have access to view the code of this framework. However, according to their explanation, they mentioned that the `'AppLovin SDK' is managed as a Pod`. Could the "duplicate classes" issue be occurring because this framework includes the AppLovin SDK?

**Comment by harryarakkal** [comment]
Yeah that's right. If their framework includes the AppLovin SDK, it could cause the duplicate classes

**Comment by ji-hyun219** [comment]
Oh, I got it..
Thank you very much for your response, @harryarakkal.
