### ISSUE TITLE
Current SDK version (11.9.0) is outdated

### ISSUE THREAD

**Issue by cameloott** [AppLovin/AppLovin-MAX-Flutter#94]
### MAX Plugin Version

2.5.0

### Flutter Version

3.7.12

### Device/Platform Info

iOS 16.1.1

### Current Behavior

I can test in android devices. But in iOS devices I get the following error:

`Current SDK version (11.9.0) is outdated. Please integrate the latest version of the AppLovin SDK (11.10.1). Doing so will improve your CPMs and ensure you have access to the latest revenue earning features.`

### How to Reproduce

As far as I can see, it is updated periodically. However, I have a time limit. Is there any short solution?

Thanks for your interesr

**Comment by thomasmso** [comment]
I've pushed a new plugin which depends on our latest native Android and iOS SDKs.

https://github.com/AppLovin/AppLovin-MAX-Flutter/releases/tag/release_2_6_0
